// frontend/admin/src/pages/login/LoginPage.tsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Box,
  Card,
  CardContent,
  CardActions,
  TextField,
  Button,
  Typography,
  Alert,
} from '@mui/material'
import type { AxiosError } from 'axios'
import { apiClientes } from '../../api/axios'

export default function LoginPage() {
  const navigate = useNavigate()
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [errorMessage, setErrorMessage] = useState('')
  const [loading, setLoading] = useState(false)

  const formValido = username.trim() !== '' && password.trim() !== ''

  async function handleLogin(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setErrorMessage('')
    try {
      const resp = await apiClientes.post('/clientes-api/v1/auth/login', { username, password })
      if (resp.status === 206) return navigate('/admin/login-2fa')
      navigate('/admin/app')
    } catch (err) {
      const error = err as AxiosError<{ message: string }>
      if (error.response) {
        setErrorMessage(error.response.data?.message ?? 'Erro ao fazer login.')
      }
    } finally {
      setLoading(false)
    }
  }

  return (
    <Box sx={{ display: 'flex', justifyContent: 'center', pt: 8, px: 2 }}>
      <Card sx={{ maxWidth: 400, width: '100%' }}>
        <CardContent>
          <Box sx={{ textAlign: 'center', mb: 2 }}>
            <Box
              component="img"
              src="/logo-arenco.png"
              alt="Arenco"
              sx={{ height: 80, maxWidth: 150 }}
            />
            <Typography variant="h6" sx={{ mt: 1 }}>
              Login
            </Typography>
          </Box>

          <Box component="form" onSubmit={handleLogin} sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
            <TextField
              label="Usuário"
              value={username}
              onChange={e => setUsername(e.target.value)}
              size="small"
              fullWidth
              required
            />
            <TextField
              label="Senha"
              type="password"
              value={password}
              onChange={e => setPassword(e.target.value)}
              size="small"
              fullWidth
              required
            />

            {errorMessage && <Alert severity="error">{errorMessage}</Alert>}

            <Button
              type="submit"
              variant="contained"
              disabled={!formValido || loading}
              loading={loading}
            >
              Entrar
            </Button>
          </Box>
        </CardContent>
        <CardActions sx={{ justifyContent: 'center' }}>
          <Button size="small" onClick={() => navigate('/admin/esqueci-minha-senha')}>
            Esqueci minha senha
          </Button>
        </CardActions>
      </Card>
    </Box>
  )
}

// frontend/admin/src/pages/login/LoginPage.vue
<template>
  <div class="page-login">
    <div class="q-pt-xl q-pa-md">
      <q-card class="q-pa-xs q-pb-lg" style="max-width: 400px; margin: auto">
        <q-card-section class="text-center">
          <q-img
            src="/logo-arenco.png"
            id="logoArenco"
            spinner-color="white"
            alt="Arenco"
            style="height: 80px; max-width: 150px"
          />
          <div class="text-h6">Login</div>
        </q-card-section>

        <q-card-section>
          <form @submit.prevent="login">
            <q-input
              v-model="username"
              label="Usuário"
              outlined
              dense
              :rules="[validaUsername]"
              lazy-rules
              class="q-mb-md full-width"
            />
            <q-input
              v-model="password"
              label="Senha"
              type="password"
              outlined
              dense
              :rules="[validaPassword]"
              lazy-rules
              class="full-width"
            />
            <q-card-actions align="center">
              <q-btn
                label="Entrar"
                color="primary"
                :disable="!formValido"
                class="q-mt-md"
                type="submit"
              />
            </q-card-actions>
          </form>
        </q-card-section>

        <q-card-section v-if="errorMessage" class="text-negative text-center">
          {{ errorMessage }}
        </q-card-section>

        <q-card-actions align="center">
          <q-btn
            flat
            color="primary"
            no-caps
            label="Esqueci minha senha"
            to="/esqueci-minha-senha"
          />
        </q-card-actions>
      </q-card>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { ref, watch } from 'vue';
  import { useRouter } from 'vue-router';
  import type { AxiosError } from 'axios';
  import { apiClientes } from 'src/boot/axios';

  const username = ref('');
  const password = ref('');
  const errorMessage = ref('');
  const router = useRouter();

  // Validações
  const validaUsername = (val: string) => !!val || 'O nome de usuário é obrigatório';
  const validaPassword = (val: string) => !!val || 'A senha é obrigatória';

  const formValido = ref(false);

  // Atualiza o estado do formulário
  watch([username, password], () => {
    formValido.value = username.value.trim() !== '' && password.value.trim() !== '';
  });

  async function login() {
    try {
      const resp = await apiClientes.post(
        '/clientes-api/v1/auth/login',
        {
          username: username.value,
          password: password.value,
        },
        {
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );
      if (resp.status === 206) {
        return router.push('/login-2fa');
      }
      return router.push('/admin/app');
    } catch (err) {
      const error = err as AxiosError<{ message: string }>;

      if (error.response) {
        errorMessage.value = error.response.data?.message;
        console.error('Erro no login:', error.response.data);
      } else {
        console.error('Erro no login:', error.message);
      }
    }
  }
</script>

<style scoped>
  .full-width {
    width: 100%;
  }

  .text-center {
    text-align: center;
  }
</style>
