// frontend/admin/src/pages/login/Login2FAPage.tsx
import { useState, useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Box,
  Card,
  CardContent,
  CardActions,
  TextField,
  Button,
  Typography,
  Alert,
  FormControl,
  InputLabel,
  Select,
  MenuItem,
  Divider,
  Collapse,
} from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import HelpIcon from '@mui/icons-material/Help'
import type { AxiosError } from 'axios'
import { apiClientes } from '../../api/axios'

type ContactMethod = 'EMAIL' | 'CELLPHONE'

interface UserContactDto {
  id: string
  contactMethod: ContactMethod
  contactValue: string
}

interface ErrorPayload {
  code?: string
  message?: string
  otpTokenValid?: boolean
}

type AlertType = { type: 'info' | 'success' | 'error'; message: string } | null

export default function Login2FAPage() {
  const navigate = useNavigate()
  const [contacts, setContacts] = useState<UserContactDto[]>([])
  const [selectedContactId, setSelectedContactId] = useState<string>('')
  const [otp, setOtp] = useState('')
  const [lastSentTo, setLastSentTo] = useState<string | null>(null)
  const [cooldown, setCooldown] = useState(0)
  const [alert, setAlert] = useState<AlertType>(null)
  const [showHelp, setShowHelp] = useState(false)
  const [loading, setLoading] = useState({ contacts: false, trigger: false, validate: false })
  const cooldownRef = useRef<number | null>(null)

  function formatLabel(c: UserContactDto) {
    return `${c.contactMethod === 'CELLPHONE' ? 'Celular' : 'E-mail'} • ${c.contactValue}`
  }

  function startCooldown(secs = 10) {
    setCooldown(secs)
    if (cooldownRef.current) clearInterval(cooldownRef.current)
    cooldownRef.current = window.setInterval(() => {
      setCooldown(prev => {
        if (prev <= 1) {
          clearInterval(cooldownRef.current!)
          cooldownRef.current = null
          return 0
        }
        return prev - 1
      })
    }, 1000)
  }

  useEffect(() => {
    loadContacts()
    return () => { if (cooldownRef.current) clearInterval(cooldownRef.current) }
  }, [])

  async function loadContacts() {
    setLoading(l => ({ ...l, contacts: true }))
    setAlert(null)
    try {
      const { data } = await apiClientes.get<UserContactDto[]>('/clientes-api/v1/otp/contacts-available')
      setContacts(data)
      if (!data.length) setAlert({ type: 'info', message: 'Nenhum contato disponível. Volte e faça login novamente.' })
      else setSelectedContactId(data[0]!.id)
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>
      setAlert({ type: 'error', message: e.response?.data?.message ?? 'Falha ao carregar contatos.' })
    } finally {
      setLoading(l => ({ ...l, contacts: false }))
    }
  }

  async function triggerOtp() {
    if (!selectedContactId) return
    setLoading(l => ({ ...l, trigger: true }))
    setAlert(null)
    try {
      await apiClientes.post('/clientes-api/v1/otp/trigger', { contactId: selectedContactId })
      const found = contacts.find(c => c.id === selectedContactId)
      setLastSentTo(found ? formatLabel(found) : null)
      setAlert({ type: 'success', message: 'Código enviado. Verifique sua caixa de entrada/SMS.' })
      startCooldown(10)
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>
      setAlert({ type: 'error', message: e.response?.data?.message ?? 'Não foi possível enviar o código.' })
      if (e.response?.status === 429) startCooldown(10)
    } finally {
      setLoading(l => ({ ...l, trigger: false }))
    }
  }

  async function validateOtp() {
    if (otp.trim().length < 4) return
    setLoading(l => ({ ...l, validate: true }))
    setAlert(null)
    try {
      await apiClientes.post('/clientes-api/v1/otp/authentication', { otp: otp.trim() })
      setAlert({ type: 'success', message: 'Verificação concluída. Redirecionando...' })
      setTimeout(() => navigate('/admin/app'), 300)
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>
      const msg = e.response?.data?.message ?? 'Falha na validação do código.'
      setAlert({ type: 'error', message: msg })
    } finally {
      setLoading(l => ({ ...l, validate: false }))
    }
  }

  async function logout() {
    try { await apiClientes.post('/clientes-api/v1/auth/logout') } catch {}
    navigate('/admin')
  }

  return (
    <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '80vh', px: 2 }}>
      <Card sx={{ maxWidth: 480, width: '100%' }}>
        <CardContent>
          <Typography variant="h6" align="center">Verificação em duas etapas</Typography>
          <Typography variant="subtitle2" align="center" color="text.secondary" sx={{ mb: 2 }}>
            Escolha um contato para receber o código
          </Typography>

          {alert && <Alert severity={alert.type} sx={{ mb: 2 }}>{alert.message}</Alert>}

          <FormControl fullWidth size="small" sx={{ mb: 1 }} disabled={loading.contacts || loading.trigger || cooldown > 0}>
            <InputLabel>Contato</InputLabel>
            <Select value={selectedContactId} label="Contato" onChange={e => setSelectedContactId(e.target.value)}>
              {contacts.map(c => (
                <MenuItem key={c.id} value={c.id}>{formatLabel(c)}</MenuItem>
              ))}
            </Select>
          </FormControl>

          <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 1 }}>
            {cooldown > 0
              ? `Aguarde ${cooldown}s para reenviar`
              : 'Selecione um contato e clique em Enviar código'}
          </Typography>

          <Button
            fullWidth
            variant="contained"
            disabled={!selectedContactId || loading.contacts || cooldown > 0}
            loading={loading.trigger}
            onClick={triggerOtp}
            sx={{ mb: 1 }}
          >
            Enviar código
          </Button>

          {lastSentTo && (
            <Typography variant="caption" color="text.secondary" display="block" sx={{ mb: 1 }}>
              Último envio para: <strong>{lastSentTo}</strong>
              {cooldown > 0 && ` — aguarde ${cooldown}s`}
            </Typography>
          )}

          <Divider sx={{ my: 2 }} />

          <TextField
            fullWidth
            size="small"
            label="Código de verificação (OTP)"
            value={otp}
            onChange={e => setOtp(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && validateOtp()}
            inputProps={{ maxLength: 10, inputMode: 'numeric' }}
            disabled={loading.validate}
            sx={{ mb: 2 }}
          />

          <Button
            fullWidth
            variant="contained"
            color="secondary"
            disabled={otp.trim().length < 4 || loading.validate}
            loading={loading.validate}
            onClick={validateOtp}
          >
            Validar código
          </Button>
        </CardContent>

        <CardActions sx={{ justifyContent: 'space-between' }}>
          <Button startIcon={<ArrowBackIcon />} onClick={logout} size="small">
            Voltar ao login
          </Button>
          <Button startIcon={<HelpIcon />} onClick={() => setShowHelp(h => !h)} size="small">
            Precisa de ajuda?
          </Button>
        </CardActions>

        <Collapse in={showHelp}>
          <Box sx={{ px: 2, pb: 2 }}>
            <Typography variant="caption" color="text.secondary">
              • Verifique caixa de entrada/SMS.<br />
              • Se não recebeu, aguarde o cooldown e tente novamente.<br />
              • Se o token expirar, peça um novo envio.
            </Typography>
          </Box>
        </Collapse>
      </Card>
    </Box>
  )
}

// frontend/admin/src/pages/login/Login2FAPage.vue
<template>
  <div class="page-login q-pa-md flex flex-center">
    <q-card class="q-pa-md" style="max-width: 480px; width: 100%">
      <q-card-section class="text-center">
        <div class="text-h6">Verificação em duas etapas</div>
        <div class="text-subtitle2 q-mt-xs">Escolha um contato para receber o código</div>
      </q-card-section>

      <!-- Avisos -->
      <q-card-section v-if="alert.message">
        <q-banner
          :class="
            alert.type === 'error'
              ? 'bg-negative text-white'
              : alert.type === 'success'
                ? 'bg-positive text-white'
                : 'bg-grey-3'
          "
          rounded
          dense
        >
          <div class="row items-center no-wrap">
            <q-icon :name="alertIcon" class="q-mr-sm" />
            <div class="col">{{ alert.message }}</div>
          </div>
        </q-banner>
      </q-card-section>

      <!-- Seleção de contato + envio -->
      <q-card-section>
        <q-select
          v-model="selectedContactId"
          :options="contactOptions"
          option-value="id"
          option-label="label"
          emit-value
          map-options
          label="Contato"
          outlined
          dense
          :loading="loading.contacts"
          :disable="loading.contacts || loading.trigger || cooldownSeconds > 0"
          :hint="
            cooldownSeconds > 0
              ? `Aguarde ${cooldownSeconds}s para reenviar`
              : 'Selecione um contato e clique em Enviar código'
          "
          class="q-mb-md"
        >
          <template #prepend>
            <q-icon name="contacts" />
          </template>
          <template #no-option>
            <q-item>
              <q-item-section class="text-grey">
                {{ loading.contacts ? 'Carregando...' : 'Nenhum contato disponível' }}
              </q-item-section>
            </q-item>
          </template>
        </q-select>

        <q-btn
          label="Enviar código"
          color="primary"
          class="full-width q-mb-sm"
          :loading="loading.trigger"
          :disable="!selectedContactId || loading.contacts || cooldownSeconds > 0"
          @click="triggerOtp"
        />

        <div class="text-caption text-grey-7 q-mb-md" v-if="lastSentTo">
          Último envio para: <b>{{ lastSentTo }}</b>
          <span v-if="cooldownSeconds > 0"> — aguarde {{ cooldownSeconds }}s</span>
        </div>
      </q-card-section>

      <q-separator spaced />

      <!-- Input do OTP -->
      <q-card-section>
        <q-input
          v-model="otp"
          label="Código de verificação (OTP)"
          outlined
          dense
          maxlength="10"
          inputmode="numeric"
          :disable="loading.validate"
          :rules="[validaOtp]"
          @keyup.enter="validateOtp"
        >
          <template #prepend>
            <q-icon name="vpn_key" />
          </template>
        </q-input>

        <q-btn
          label="Validar código"
          color="secondary"
          class="full-width q-mt-md"
          :loading="loading.validate"
          :disable="!isOtpReady || loading.validate"
          @click="validateOtp"
        />
      </q-card-section>

      <!-- Rodapé -->
      <q-card-actions align="between">
        <q-btn flat icon="arrow_back" label="Voltar ao login" @click="logout" />
        <q-btn flat icon="help" label="Precisa de ajuda?" @click="showHelp = !showHelp" />
      </q-card-actions>

      <q-slide-transition>
        <div v-show="showHelp" class="q-pa-md text-caption text-grey-7">
          • Verifique caixa de entrada/SMS.<br />
          • Se não recebeu, aguarde o cooldown e tente novamente.<br />
          • Se o token expirar, peça um novo envio.
        </div>
      </q-slide-transition>
    </q-card>
  </div>
</template>

<script setup lang="ts">
  import { ref, computed, onMounted, onBeforeUnmount } from 'vue';
  import { useRouter } from 'vue-router';
  import { apiClientes } from 'src/boot/axios';
  import type { AxiosError } from 'axios';

  type ContactMethod = 'EMAIL' | 'CELLPHONE';

  interface UserContactDto {
    id: string;
    contactMethod: ContactMethod;
    contactValue: string;
  }

  interface TriggerResponse {
    result: 'SUCCESS' | 'FAIL';
    userContactDto: UserContactDto;
    message: string; // ex: "QUEUED"
  }

  interface ErrorPayload {
    code?: string; // "429 TOO_MANY_REQUESTS" | "401 UNAUTHORIZED" | "400 BAD_REQUEST" | ...
    message?: string; // mensagem amigável do back
    otpTokenValid?: boolean; // presente em 400 BAD_REQUEST
  }

  const router = useRouter();

  const loading = ref({
    contacts: false,
    trigger: false,
    validate: false,
  });

  const contacts = ref<UserContactDto[]>([]);
  const selectedContactId = ref<string | null>(null);
  const otp = ref('');
  const lastSentTo = ref<string | null>(null);

  const cooldownSeconds = ref(0);
  let cooldownTimer: number | null = null;

  const showHelp = ref(false);

  const alert = ref<
    { type: 'info' | 'success' | 'error'; message: string } | { type: null; message: '' }
  >({
    type: null,
    message: '',
  });

  const alertIcon = computed(() => {
    if (alert.value.type === 'error') return 'error';
    if (alert.value.type === 'success') return 'check_circle';
    return 'info';
  });

  const contactOptions = computed(() =>
    contacts.value.map((c) => ({
      ...c,
      label: formatContactLabel(c),
    }))
  );

  const isOtpReady = computed(() => otp.value.trim().length >= 4); // ajuste se seu OTP tiver tamanho fixo

  function setAlert(type: 'info' | 'success' | 'error', message: string) {
    alert.value = { type, message };
  }

  function clearAlert() {
    alert.value = { type: null, message: '' } as never;
  }

  function formatContactLabel(c: UserContactDto) {
    // exibe algo do tipo: "Celular • +55169XXXXX27" ou "E-mail • f*****i@..."
    const prefix = c.contactMethod === 'CELLPHONE' ? 'Celular' : 'E-mail';
    return `${prefix} • ${c.contactValue}`;
  }

  async function logout() {
    try {
      await apiClientes.post('/clientes-api/v1/auth/logout');
    } catch (error) {
      console.error('Erro ao fazer logout:', error);
    } finally {
      // Limpa os tokens e redireciona para login
      router.push('/login');
    }
  }

  async function loadContacts() {
    loading.value.contacts = true;
    clearAlert();
    try {
      const { data } = await apiClientes.get<UserContactDto[]>(
        '/clientes-api/v1/otp/contacts-available'
      );
      contacts.value = data;
      if (contacts.value.length === 0 || !contacts.value[0]) {
        setAlert('info', 'Nenhum contato disponível. Volte e faça login novamente.');
      } else if (!selectedContactId.value) {
        selectedContactId.value = contacts.value[0].id;
      }
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>;
      setAlert('error', e.response?.data?.message || 'Falha ao carregar contatos.');
    } finally {
      loading.value.contacts = false;
    }
  }

  function startCooldown(seconds = 10) {
    cooldownSeconds.value = seconds;
    if (cooldownTimer) {
      window.clearInterval(cooldownTimer);
    }
    cooldownTimer = window.setInterval(() => {
      if (cooldownSeconds.value <= 1) {
        window.clearInterval(cooldownTimer!);
        cooldownTimer = null;
        cooldownSeconds.value = 0;
      } else {
        cooldownSeconds.value -= 1;
      }
    }, 1000);
  }

  async function triggerOtp() {
    if (!selectedContactId.value) return;
    loading.value.trigger = true;
    clearAlert();
    try {
      await apiClientes.post<TriggerResponse>(`/clientes-api/v1/otp/trigger`, {
        contactId: selectedContactId.value,
      });
      lastSentTo.value = contacts.value.find((c) => c.id === selectedContactId.value)
        ? formatContactLabel(contacts.value.find((c) => c.id === selectedContactId.value)!)
        : null;
      setAlert('success', 'Código enviado. Verifique sua caixa de entrada/SMS.');
      startCooldown(10); // conforme sua API retorna na mensagem de 429
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>;
      const statusMsg = e.response?.data?.message || 'Não foi possível enviar o código.';
      if (e.response?.status === 429) {
        setAlert('error', statusMsg); // ex: "aguarde mais 10 segundos..."
        // inicia cooldown mínimo de segurança (se quiser extrair o número da mensagem, pode parsear aqui)
        startCooldown(10);
      } else {
        setAlert('error', statusMsg);
      }
    } finally {
      loading.value.trigger = false;
    }
  }

  const validaOtp = (val: string) => !!val?.trim() || 'Informe o código enviado';

  async function validateOtp() {
    if (!isOtpReady.value) return;
    loading.value.validate = true;
    clearAlert();
    try {
      await apiClientes.post('/clientes-api/v1/otp/authentication', {
        otp: otp.value.trim(),
      });
      setAlert('success', 'Verificação concluída. Redirecionando...');
      // pequeno delay para UX antes do push
      setTimeout(() => router.push('/admin/app'), 300);
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>;
      const code = e.response?.data?.code || '';
      const msg = e.response?.data?.message || 'Falha na validação do código.';
      if (code.startsWith('401')) {
        // token inexistente/expirado/inválido -> peça novo envio
        setAlert('error', msg + ' Solicite um novo código.');
      } else if (code.startsWith('400')) {
        setAlert('error', msg); // exibe "Token Inválido. Restam 2 tentativas"
      } else {
        setAlert('error', msg);
      }
    } finally {
      loading.value.validate = false;
    }
  }

  onMounted(() => {
    loadContacts();
  });

  onBeforeUnmount(() => {
    if (cooldownTimer) {
      window.clearInterval(cooldownTimer);
      cooldownTimer = null;
    }
  });
</script>

<style scoped>
  .page-login {
    min-height: 80vh;
  }
  .full-width {
    width: 100%;
  }
</style>
