// frontend/admin/src/pages/misc/WorkInProgress.vue
<template>
  <q-page class="flex flex-center bg-grey-2">
    <div class="text-center q-pa-xl">
      <q-icon name="construction" size="100px" color="orange-8" />
      <h1 class="text-h4 q-mt-md">Página em Construção</h1>
      <p class="text-subtitle1 q-mt-sm">
        Estamos trabalhando para trazer algo incrível. Volte em breve!
      </p>
    </div>
  </q-page>
</template>

<script setup></script>

// frontend/admin/src/pages/misc/WorkInProgress.tsx
import { Box, Typography } from '@mui/material'
import ConstructionIcon from '@mui/icons-material/Construction'

export default function WorkInProgress() {
  return (
    <Box
      sx={{
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: '60vh',
        bgcolor: 'grey.100',
        borderRadius: 2,
        p: 4,
      }}
    >
      <ConstructionIcon sx={{ fontSize: 100, color: 'warning.dark', mb: 2 }} />
      <Typography variant="h4" gutterBottom>
        Página em Construção
      </Typography>
      <Typography variant="subtitle1" color="text.secondary">
        Estamos trabalhando para trazer algo incrível. Volte em breve!
      </Typography>
    </Box>
  )
}
