// frontend/admin/src/layouts/MainLayout.vue
<template>
  <q-layout view="hHh lpR fFf">
    <!-- Cabeçalho -->
    <q-header reveal elevated class="text-white">
      <q-toolbar>
        <q-btn dense flat icon="menu" aria-label="Abrir menu" @click="toggleLeftDrawer" />
        <q-toolbar-title class="q-mx-auto flex flex-center">
          <q-img
            src="/logo-arenco.png"
            @click="goToPage('/admin/app')"
            id="logoArenco"
            spinner-color="white"
            alt="Arenco"
            style="height: 80px; max-width: 150px; cursor: pointer"
          />
        </q-toolbar-title>
      </q-toolbar>
    </q-header>

    <!-- Menu Lateral -->
    <q-drawer show-if-above v-model="leftDrawerOpen" side="left" elevated>
      <q-list padding>
        <q-item clickable v-ripple @click="goToPage('/admin/app')" aria-label="Home">
          <q-item-section avatar><q-icon name="home" /></q-item-section>
          <q-item-section>Home</q-item-section>
        </q-item>

        <q-separator spaced />

        <!-- Clientes -->
        <q-expansion-item icon="people" label="Clientes" expand-separator dense>
          <q-item
            :to="{ path: '/admin/app/clientes' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="person" /></q-item-section>
            <q-item-section>Clientes</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/enderecos' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="place" /></q-item-section>
            <q-item-section>Endereços</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/contatos' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="contact_phone" /></q-item-section>
            <q-item-section>Contatos</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/preferencias-contatos' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="tune" /></q-item-section>
            <q-item-section>Preferências de contato</q-item-section>
          </q-item>
        </q-expansion-item>

        <q-separator spaced />

        <!-- Contratos -->
        <q-expansion-item icon="description" label="Contratos" expand-separator dense>
          <q-item
            :to="{ path: '/admin/app/contratos' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="description" /></q-item-section>
            <q-item-section>Contratos</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/a-receber' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar>
              <q-icon name="request_page" />
            </q-item-section>

            <!-- Texto alinhado à esquerda -->
            <q-item-section> A Receber </q-item-section>

            <!-- Badge alinhado à direita -->
            <q-item-section side v-if="kpis?.titulosVencendoHoje">
              <q-badge color="negative" outline>
                {{ kpis.titulosVencendoHoje }}
              </q-badge>
            </q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/recebidos' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="check_circle" /></q-item-section>
            <q-item-section>Recebidos</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/boletos' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="receipt_long" /></q-item-section>
            <q-item-section>Boletos</q-item-section>
          </q-item>
        </q-expansion-item>

        <q-separator spaced />

        <!-- Sincronizações -->
        <q-expansion-item icon="sync" label="Sincronizações" expand-separator dense>
          <q-item
            :to="{ path: '/admin/app/sincronizacoes/bases' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="storage" /></q-item-section>
            <q-item-section>Sincronização de Bases</q-item-section>
          </q-item>

          <q-item
            :to="{ path: '/admin/app/sincronizacoes/boletos' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="receipt_long" /></q-item-section>
            <q-item-section>Sincronização de Boletos</q-item-section>
          </q-item>
        </q-expansion-item>

        <q-separator spaced />

        <!-- Mensageria -->
        <q-expansion-item icon="mark_email_unread" label="Mensageria" expand-separator dense>
          <q-item
            :to="{ path: '/admin/app/emails-enviados' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="mail" /></q-item-section>
            <q-item-section>E-mails enviados</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/sms-enviados' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="sms" /></q-item-section>
            <q-item-section>SMS enviados</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/templates-email' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
          >
            <q-item-section avatar><q-icon name="drafts" /></q-item-section>
            <q-item-section>Templates de e-mail</q-item-section>
          </q-item>
        </q-expansion-item>

        <q-separator spaced />

        <!-- Segurança -->
        <q-expansion-item icon="security" label="Segurança" expand-separator dense>
          <q-item
            :to="{ path: '/admin/app/sessoes-ativas' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
            v-if="can('security.sessions:view')"
          >
            <q-item-section avatar><q-icon name="schedule" /></q-item-section>
            <q-item-section>Sessões ativas</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/atividades-suspeitas' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
            v-if="can('security.threats:view')"
          >
            <q-item-section avatar><q-icon name="warning" /></q-item-section>
            <q-item-section>Atividades suspeitas</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/ips-bloqueados' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
            v-if="can('security.ips:view')"
          >
            <q-item-section avatar><q-icon name="block" /></q-item-section>
            <q-item-section>IPs bloqueados</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/usuarios-bloqueados' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
            v-if="can('security.users:view')"
          >
            <q-item-section avatar><q-icon name="person_off" /></q-item-section>
            <q-item-section>Usuários bloqueados</q-item-section>
          </q-item>
        </q-expansion-item>

        <q-separator spaced />

        <!-- Configurações -->
        <q-expansion-item icon="settings" label="Configurações" expand-separator dense>
          <q-item
            :to="{ path: '/admin/app/administradores' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
            v-if="can('admins:view')"
          >
            <q-item-section avatar><q-icon name="supervisor_account" /></q-item-section>
            <q-item-section>Administradores</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/config-envios-automaticos' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
            v-if="can('messaging:auto-config:view')"
          >
            <q-item-section avatar><q-icon name="send" /></q-item-section>
            <q-item-section>Configurações de envios automáticos</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/config-boletos' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
            v-if="can('billing:slips-config:view')"
          >
            <q-item-section avatar><q-icon name="receipt_long" /></q-item-section>
            <q-item-section>Configurações de geração de boletos</q-item-section>
          </q-item>
          <q-item
            :to="{ path: '/admin/app/config-login' }"
            clickable
            v-ripple
            exact
            active-class="text-primary"
            v-if="can('security:login-config:view')"
          >
            <q-item-section avatar><q-icon name="login" /></q-item-section>
            <q-item-section>Configurações de login</q-item-section>
          </q-item>
        </q-expansion-item>

        <q-separator spaced />

        <!-- Sair -->
        <q-item clickable v-ripple @click="logout" aria-label="Sair da aplicação">
          <q-item-section avatar><q-icon name="logout" /></q-item-section>
          <q-item-section>Sair</q-item-section>
        </q-item>
      </q-list>
    </q-drawer>

    <!-- Conteúdo -->
    <q-page-container>
      <router-view />
    </q-page-container>
  </q-layout>
</template>

<script>
  import { ref } from 'vue';
  import { useRouter } from 'vue-router';
  import { apiClientes } from 'src/boot/axios';

  export default {
    setup() {
      const leftDrawerOpen = ref(false);
      const router = useRouter();

      // AGORA visíveis no template:
      const can = (p) => true;
      const kpis = { titulosVencendoHoje: 3 };

      function toggleLeftDrawer() {
        leftDrawerOpen.value = !leftDrawerOpen.value;
      }

      function goToPage(path) {
        router.push(path);
      }

      async function logout() {
        try {
          await apiClientes.post('/clientes-api/v1/auth/logout');
        } catch (error) {
          console.error('Erro ao fazer logout:', error);
        } finally {
          // Limpa os tokens e redireciona para login
          router.push('/login');
        }
      }

      return {
        leftDrawerOpen,
        toggleLeftDrawer,
        goToPage,
        logout,
        can,
        kpis,
      };
    },
  };
</script>
<style>
  .q-drawer__content {
    box-sizing: border-box;
    overflow-y: auto;
  }

  /* Aplica padding-top só em telas pequenas */
  @media (max-width: 1023px) {
    .q-drawer__content {
      padding-top: 80px; /* altura do header no mobile */
    }
  }

  /* Para telas maiores, remove o padding ou reduz */
  @media (min-width: 1024px) {
    .q-drawer__content {
      padding-top: 0; /* ou um valor menor, se quiser */
    }
  }
</style>

<style scoped>
  .q-toolbar-title {
    font-weight: bold;
    font-size: 18px;
  }

  .q-header {
    z-index: 10;
  }

  .q-drawer {
    background-color: #f5f5f5;
  }

  .q-item {
    font-size: 16px;
  }
</style>

// frontend/admin/src/layouts/MainLayout.tsx
import { useState, useEffect } from 'react'
import { Outlet, useNavigate, useLocation } from 'react-router-dom'
import {
  AppBar,
  Box,
  CssBaseline,
  Drawer,
  IconButton,
  List,
  ListItemButton,
  ListItemIcon,
  ListItemText,
  Toolbar,
  Collapse,
  Divider,
  Badge,
  CircularProgress,
} from '@mui/material'
import MenuIcon from '@mui/icons-material/Menu'
import HomeIcon from '@mui/icons-material/Home'
import PeopleIcon from '@mui/icons-material/People'
import PersonIcon from '@mui/icons-material/Person'
import PlaceIcon from '@mui/icons-material/Place'
import ContactPhoneIcon from '@mui/icons-material/ContactPhone'
import TuneIcon from '@mui/icons-material/Tune'
import DescriptionIcon from '@mui/icons-material/Description'
import RequestPageIcon from '@mui/icons-material/RequestPage'
import CheckCircleIcon from '@mui/icons-material/CheckCircle'
import ReceiptLongIcon from '@mui/icons-material/ReceiptLong'
import SyncIcon from '@mui/icons-material/Sync'
import StorageIcon from '@mui/icons-material/Storage'
import MarkEmailUnreadIcon from '@mui/icons-material/MarkEmailUnread'
import MailIcon from '@mui/icons-material/Mail'
import SmsIcon from '@mui/icons-material/Sms'
import DraftsIcon from '@mui/icons-material/Drafts'
import SecurityIcon from '@mui/icons-material/Security'
import ScheduleIcon from '@mui/icons-material/Schedule'
import WarningIcon from '@mui/icons-material/Warning'
import BlockIcon from '@mui/icons-material/Block'
import PersonOffIcon from '@mui/icons-material/PersonOff'
import SettingsIcon from '@mui/icons-material/Settings'
import SupervisorAccountIcon from '@mui/icons-material/SupervisorAccount'
import SendIcon from '@mui/icons-material/Send'
import LoginIcon from '@mui/icons-material/Login'
import LogoutIcon from '@mui/icons-material/Logout'
import ExpandLessIcon from '@mui/icons-material/ExpandLess'
import ExpandMoreIcon from '@mui/icons-material/ExpandMore'
import { apiClientes } from '../api/axios'
import { useAuthCheck } from '../hooks/useAuthGuard'
import { Navigate } from 'react-router-dom'

const DRAWER_WIDTH = 280

const can = (_perm?: string) => true
const kpis = { titulosVencendoHoje: 3 }

interface NavGroup {
  id: string
  label: string
  icon: React.ReactNode
  items: { label: string; path: string; icon: React.ReactNode; badge?: number; show?: boolean }[]
}

const navGroups: NavGroup[] = [
  {
    id: 'clientes',
    label: 'Clientes',
    icon: <PeopleIcon />,
    items: [
      { label: 'Clientes', path: '/admin/app/clientes', icon: <PersonIcon /> },
      { label: 'Endereços', path: '/admin/app/enderecos', icon: <PlaceIcon /> },
      { label: 'Contatos', path: '/admin/app/contatos', icon: <ContactPhoneIcon /> },
      {
        label: 'Preferências de contato',
        path: '/admin/app/preferencias-contatos',
        icon: <TuneIcon />,
      },
    ],
  },
  {
    id: 'contratos',
    label: 'Contratos',
    icon: <DescriptionIcon />,
    items: [
      { label: 'Contratos', path: '/admin/app/contratos', icon: <DescriptionIcon /> },
      {
        label: 'A Receber',
        path: '/admin/app/a-receber',
        icon: <RequestPageIcon />,
        badge: kpis.titulosVencendoHoje,
      },
      { label: 'Recebidos', path: '/admin/app/recebidos', icon: <CheckCircleIcon /> },
      { label: 'Boletos', path: '/admin/app/boletos', icon: <ReceiptLongIcon /> },
    ],
  },
  {
    id: 'sincronizacoes',
    label: 'Sincronizações',
    icon: <SyncIcon />,
    items: [
      {
        label: 'Sincronização de Bases',
        path: '/admin/app/sincronizacoes/bases',
        icon: <StorageIcon />,
      },
      {
        label: 'Sincronização de Boletos',
        path: '/admin/app/sincronizacoes/boletos',
        icon: <ReceiptLongIcon />,
      },
    ],
  },
  {
    id: 'mensageria',
    label: 'Mensageria',
    icon: <MarkEmailUnreadIcon />,
    items: [
      { label: 'E-mails enviados', path: '/admin/app/emails-enviados', icon: <MailIcon /> },
      { label: 'SMS enviados', path: '/admin/app/sms-enviados', icon: <SmsIcon /> },
      { label: 'Templates de e-mail', path: '/admin/app/templates-email', icon: <DraftsIcon /> },
    ],
  },
  {
    id: 'seguranca',
    label: 'Segurança',
    icon: <SecurityIcon />,
    items: [
      {
        label: 'Sessões ativas',
        path: '/admin/app/sessoes-ativas',
        icon: <ScheduleIcon />,
        show: can('security.sessions:view'),
      },
      {
        label: 'Atividades suspeitas',
        path: '/admin/app/atividades-suspeitas',
        icon: <WarningIcon />,
        show: can('security.threats:view'),
      },
      {
        label: 'IPs bloqueados',
        path: '/admin/app/ips-bloqueados',
        icon: <BlockIcon />,
        show: can('security.ips:view'),
      },
      {
        label: 'Usuários bloqueados',
        path: '/admin/app/usuarios-bloqueados',
        icon: <PersonOffIcon />,
        show: can('security.users:view'),
      },
    ],
  },
  {
    id: 'configuracoes',
    label: 'Configurações',
    icon: <SettingsIcon />,
    items: [
      {
        label: 'Administradores',
        path: '/admin/app/administradores',
        icon: <SupervisorAccountIcon />,
        show: can('admins:view'),
      },
      {
        label: 'Configurações de envios automáticos',
        path: '/admin/app/config-envios-automaticos',
        icon: <SendIcon />,
        show: can('messaging:auto-config:view'),
      },
      {
        label: 'Configurações de boletos',
        path: '/admin/app/config-boletos',
        icon: <ReceiptLongIcon />,
        show: can('billing:slips-config:view'),
      },
      {
        label: 'Configurações de login',
        path: '/admin/app/config-login',
        icon: <LoginIcon />,
        show: can('security:login-config:view'),
      },
    ],
  },
]

export default function MainLayout() {
  const authState = useAuthCheck()
  const navigate = useNavigate()
  const location = useLocation()
  const [mobileOpen, setMobileOpen] = useState(false)
  const [openGroups, setOpenGroups] = useState<Record<string, boolean>>({
    clientes: true,
    contratos: true,
  })

  useEffect(() => {
    if (authState === 'PENDING_2FA') navigate('/admin/login-2fa', { replace: true })
    if (authState === 'NO_SESSION' || authState === 'FORBIDDEN')
      navigate('/admin', { replace: true })
  }, [authState, navigate])

  if (authState === 'loading') {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: '100vh' }}>
        <CircularProgress />
      </Box>
    )
  }

  if (authState !== 'AUTH_OK') return <Navigate to="/admin" replace />

  function toggleGroup(id: string) {
    setOpenGroups(prev => ({ ...prev, [id]: !prev[id] }))
  }

  async function logout() {
    try {
      await apiClientes.post('/clientes-api/v1/auth/logout')
    } catch {}
    navigate('/admin')
  }

  const drawerContent = (
    <Box sx={{ overflow: 'auto' }}>
      <List dense>
        <ListItemButton onClick={() => navigate('/admin/app/home')}>
          <ListItemIcon>
            <HomeIcon />
          </ListItemIcon>
          <ListItemText primary="Home" />
        </ListItemButton>

        <Divider sx={{ my: 0.5 }} />

        {navGroups.map(group => (
          <Box key={group.id}>
            <ListItemButton onClick={() => toggleGroup(group.id)}>
              <ListItemIcon>{group.icon}</ListItemIcon>
              <ListItemText primary={group.label} />
              {openGroups[group.id] ? <ExpandLessIcon /> : <ExpandMoreIcon />}
            </ListItemButton>
            <Collapse in={!!openGroups[group.id]} timeout="auto" unmountOnExit>
              <List dense disablePadding>
                {group.items
                  .filter(item => item.show !== false)
                  .map(item => (
                    <ListItemButton
                      key={item.path}
                      sx={{ pl: 4 }}
                      selected={location.pathname === item.path}
                      onClick={() => {
                        navigate(item.path)
                        setMobileOpen(false)
                      }}
                    >
                      <ListItemIcon sx={{ minWidth: 36 }}>
                        {item.badge ? (
                          <Badge badgeContent={item.badge} color="error">
                            {item.icon}
                          </Badge>
                        ) : (
                          item.icon
                        )}
                      </ListItemIcon>
                      <ListItemText primary={item.label} />
                    </ListItemButton>
                  ))}
              </List>
            </Collapse>
            <Divider sx={{ my: 0.5 }} />
          </Box>
        ))}

        <ListItemButton onClick={logout}>
          <ListItemIcon>
            <LogoutIcon />
          </ListItemIcon>
          <ListItemText primary="Sair" />
        </ListItemButton>
      </List>
    </Box>
  )

  return (
    <Box sx={{ display: 'flex' }}>
      <CssBaseline />

      <AppBar position="fixed" sx={{ zIndex: theme => theme.zIndex.drawer + 1 }}>
        <Toolbar>
          <IconButton
            color="inherit"
            aria-label="Abrir menu"
            edge="start"
            onClick={() => setMobileOpen(prev => !prev)}
            sx={{ mr: 2, display: { lg: 'none' } }}
          >
            <MenuIcon />
          </IconButton>
          <Box sx={{ flex: 1, display: 'flex', justifyContent: 'center' }}>
            <Box
              component="img"
              src="/logo-arenco.png"
              alt="Arenco"
              onClick={() => navigate('/admin/app/home')}
              sx={{ height: 56, maxWidth: 140, cursor: 'pointer', objectFit: 'contain' }}
            />
          </Box>
        </Toolbar>
      </AppBar>

      {/* Mobile drawer */}
      <Drawer
        variant="temporary"
        open={mobileOpen}
        onClose={() => setMobileOpen(false)}
        ModalProps={{ keepMounted: true }}
        sx={{
          display: { xs: 'block', lg: 'none' },
          '& .MuiDrawer-paper': { width: DRAWER_WIDTH, boxSizing: 'border-box' },
        }}
      >
        <Toolbar />
        {drawerContent}
      </Drawer>

      {/* Desktop drawer */}
      <Drawer
        variant="permanent"
        sx={{
          display: { xs: 'none', lg: 'block' },
          '& .MuiDrawer-paper': { width: DRAWER_WIDTH, boxSizing: 'border-box' },
        }}
        open
      >
        <Toolbar />
        {drawerContent}
      </Drawer>

      <Box
        component="main"
        sx={{ flexGrow: 1, p: 3, width: { lg: `calc(100% - ${DRAWER_WIDTH}px)` } }}
      >
        <Toolbar />
        <Outlet />
      </Box>
    </Box>
  )
}
