// frontend/admin/src/pages/contratos/ContratoDetalhesPage.vue
<template>
  <div class="q-pa-md q-mt-lg">
    <q-btn label="Voltar" icon="arrow_back" flat @click="router.back()" class="q-mb-md" />

    <!-- Detalhes -->
    <ContratoDetalhesCard v-if="contrato" :contrato="contrato" />

    <div v-if="carregando">
      <q-spinner />
    </div>

    <div v-else-if="!contrato">
      <q-banner type="warning" label="Contrato não encontrado." />
    </div>
  </div>
</template>

<script setup lang="ts">
  import { ref, onMounted } from 'vue';
  import { useRoute, useRouter } from 'vue-router';
  import { apiClientes } from 'src/boot/axios';
  import ContratoDetalhesCard from 'src/components/ContratoDetalhesCard.vue';

  const route = useRoute();
  const router = useRouter();

  const contrato = ref<any | null>(null);
  const carregando = ref(true);

  async function carregarDetalhes() {
    const id = route.query.id;
    if (!id || typeof id !== 'string') {
      carregando.value = false;
      return;
    }

    try {
      const headers = {};

      const response = await apiClientes.get(`/clientes-api/v1/admin/contratos?id=${id}`, {
        headers,
      });
      contrato.value = response.data;
    } catch (err) {
      console.error('Erro ao carregar titulo:', err);
    } finally {
      carregando.value = false;
    }
  }

  onMounted(carregarDetalhes);
</script>

// frontend/admin/src/pages/contratos/ContratoDetalhesPage.tsx
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { Box, Button, CircularProgress, Alert } from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import { apiClientes } from '../../api/axios'
import { ContratoDetalhesCard } from '../../components/ContratoDetalhesCard'

export default function ContratoDetalhesPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const [contrato, setContrato] = useState<Record<string, unknown> | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!id) { setLoading(false); return }
    apiClientes.get(`/clientes-api/v1/admin/contratos?id=${id}`)
      .then(resp => setContrato(resp.data))
      .catch(err => console.error('Erro ao carregar contrato:', err))
      .finally(() => setLoading(false))
  }, [id])

  return (
    <Box>
      <Button startIcon={<ArrowBackIcon />} onClick={() => navigate(-1)} sx={{ mb: 2 }}>Voltar</Button>
      {loading && <CircularProgress />}
      {!loading && !contrato && <Alert severity="warning">Contrato não encontrado.</Alert>}
      {!loading && contrato && <ContratoDetalhesCard contrato={contrato} />}
    </Box>
  )
}
