// frontend/admin/src/pages/contratos/TitulosRecebidosDetalhesPage.tsx
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { Box, Button, CircularProgress, Alert } from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import { apiClientes } from '../../api/axios'
import { TituloRecebidoDetalhesCard } from '../../components/TituloRecebidoDetalhesCard'

export default function TitulosRecebidosDetalhesPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const [titulo, setTitulo] = useState<Record<string, unknown> | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!id) { setLoading(false); return }
    apiClientes.get(`/clientes-api/v1/admin/recebidos?id=${id}`)
      .then(resp => setTitulo(resp.data))
      .catch(err => console.error('Erro ao carregar título:', err))
      .finally(() => setLoading(false))
  }, [id])

  return (
    <Box>
      <Button startIcon={<ArrowBackIcon />} onClick={() => navigate(-1)} sx={{ mb: 2 }}>Voltar</Button>
      {loading && <CircularProgress />}
      {!loading && !titulo && <Alert severity="warning">Título não encontrado.</Alert>}
      {!loading && titulo && <TituloRecebidoDetalhesCard titulo={titulo} />}
    </Box>
  )
}

// frontend/admin/src/pages/contratos/TitulosRecebidosDetalhesPage.vue
<template>
  <div class="q-pa-md q-mt-lg">
    <q-btn label="Voltar" icon="arrow_back" flat @click="router.back()" class="q-mb-md" />

    <!-- Detalhes do titulo -->
    <TituloRecebidoDetalhesCard v-if="titulo" :titulo="titulo" />

    <div v-if="carregando">
      <q-spinner />
    </div>

    <div v-else-if="!titulo">
      <q-banner type="warning" label="Titulo não encontrado." />
    </div>
  </div>
</template>

<script setup lang="ts">
  import { ref, onMounted } from 'vue';
  import { useRoute, useRouter } from 'vue-router';
  import { apiClientes } from 'src/boot/axios';
  import TituloRecebidoDetalhesCard from 'src/components/TituloRecebidoDetalhesCard.vue';

  const route = useRoute();
  const router = useRouter();

  const titulo = ref<any | null>(null);
  const carregando = ref(true);

  async function carregarTituloRecebidos() {
    const id = route.query.id;
    if (!id || typeof id !== 'string') {
      carregando.value = false;
      return;
    }

    try {
      const headers = {};

      const tituloResp = await apiClientes.get(`/clientes-api/v1/admin/recebidos?id=${id}`, {
        headers,
      });
      titulo.value = tituloResp.data;
    } catch (err) {
      console.error('Erro ao carregar titulo:', err);
    } finally {
      carregando.value = false;
    }
  }

  onMounted(carregarTituloRecebidos);
</script>
