// frontend/admin/src/pages/contratos/TitulosAReceberDetalhesPage.vue
<template>
  <div class="q-pa-md q-mt-lg">
    <q-btn label="Voltar" icon="arrow_back" flat @click="router.back()" class="q-mb-md" />

    <div v-if="carregando">
      <q-spinner />
    </div>

    <div v-else-if="!titulo">
      <q-banner type="warning" label="Título não encontrado." />
    </div>

    <div v-else>
      <TituloAReceberDetalhesCard :titulo="titulo" />
    </div>
  </div>
</template>

<script setup lang="ts">
  import { ref, onMounted } from 'vue';
  import { useRoute, useRouter } from 'vue-router';
  import { apiClientes } from 'src/boot/axios';
  import TituloAReceberDetalhesCard from 'src/components/TituloAReceberDetalhesCard.vue';

  interface Titulo {
    id: string;
    // Adicione aqui outras propriedades conforme necessário
  }

  const route = useRoute();
  const router = useRouter();

  const titulo = ref<Titulo | null>(null);
  const carregando = ref(true);

  onMounted(() => {
    carregarTituloAReceber();
  });

  async function carregarTituloAReceber() {
    const id = route.query.id;
    if (!id || typeof id !== 'string') {
      carregando.value = false;
      return;
    }

    try {
      const headers = {};
      const url = `/clientes-api/v1/admin/a-receber?id=${id}`;
      const { data } = await apiClientes.get<Titulo>(url, { headers });
      titulo.value = data;
    } catch (err) {
      console.error('Erro ao carregar título:', err);
    } finally {
      carregando.value = false;
    }
  }
</script>

// frontend/admin/src/pages/contratos/TitulosAReceberDetalhesPage.tsx
import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { Box, Button, CircularProgress, Alert } from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import { apiClientes } from '../../api/axios'
import { TituloAReceberDetalhesCard } from '../../components/TituloAReceberDetalhesCard'

export default function TitulosAReceberDetalhesPage() {
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const [titulo, setTitulo] = useState<Record<string, unknown> | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    if (!id) { setLoading(false); return }
    apiClientes.get(`/clientes-api/v1/admin/a-receber?id=${id}`)
      .then(resp => setTitulo(resp.data))
      .catch(err => console.error('Erro ao carregar título:', err))
      .finally(() => setLoading(false))
  }, [id])

  return (
    <Box>
      <Button startIcon={<ArrowBackIcon />} onClick={() => navigate(-1)} sx={{ mb: 2 }}>Voltar</Button>
      {loading && <CircularProgress />}
      {!loading && !titulo && <Alert severity="warning">Título não encontrado.</Alert>}
      {!loading && titulo && <TituloAReceberDetalhesCard titulo={titulo} />}
    </Box>
  )
}
