// frontend/admin/src/pages/configuracoes/AdministradoresPage.vue
<template>
  <div class="q-pa-md">
    <h1 class="q-mt-lg q-mb-md">Administradores</h1>

    <!-- Tabela -->
    <q-table
      :rows="usuarios"
      :columns="columns"
      row-key="id"
      :loading="loading"
      v-model:pagination="pagination"
      @request="fetchApi"
      no-data-label="Nenhum usuário encontrado."
    >
      <!-- Coluna de Ações -->
      <template v-slot:body-cell-actions="props">
        <q-td :props="props">
          <q-btn flat round dense icon="more_vert">
            <q-menu>
              <q-list style="min-width: 200px">
                <q-item clickable v-close-popup @click="removerUsuario(props, props.row)">
                  <q-item-section avatar>
                    <q-icon name="delete" color="primary" />
                  </q-item-section>
                  <q-item-section> Remover Usuário </q-item-section>
                </q-item>
              </q-list>
            </q-menu>
          </q-btn>
        </q-td>
      </template>
    </q-table>
  </div>
</template>

<script setup lang="ts">
  import { ref, watch } from 'vue';
  import { useRouter } from 'vue-router';
  import { apiClientes } from 'src/boot/axios';
  import { useQuasar } from 'quasar';

  const $q = useQuasar();

  const usuarios = ref([]);
  const loading = ref(false);
  const router = useRouter();

  const pagination = ref({
    page: 1,
    rowsPerPage: 10,
    rowsNumber: 0,
  });

  // Configuração das colunas
  const columns = [
    { name: 'nome', align: 'left' as const, label: 'Nome', field: 'name' },
    { name: 'username', align: 'left' as const, label: 'Username', field: 'username' },
    { name: 'loginMethod', align: 'left' as const, label: 'Método de Login', field: 'loginMethod' },
    { name: 'enabled', align: 'left' as const, label: 'Habilitado', field: 'enabled' },
    { name: 'actions', align: 'center' as const, label: 'Ações', field: 'actions' },
  ];

  const fetchApi = async (props: any) => {
    loading.value = true;
    try {
      if (!props.pagination) pagination.value.rowsPerPage = 10;
      else pagination.value.rowsPerPage = props.pagination.rowsPerPage;

      if (!props.pagination) pagination.value.page = 1;
      else pagination.value.page = props.pagination.page;

      const response = await apiClientes.get(
        `/clientes-api/v1/admin-management/users?page=${pagination.value.page}&size=${pagination.value.rowsPerPage}`,
        {
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      usuarios.value = response.data.content;
      pagination.value.rowsNumber = response.data.totalElements || 0;
    } catch (error: any) {
      if (error.response?.status === 403) {
        router.push('/login');
      } else {
        console.error('Erro ao buscar administradores:', error);
      }
    } finally {
      loading.value = false;
    }
  };

  watch(pagination, fetchApi, { immediate: true });

  const removerUsuario = async (props: any, usuario: any) => {
    try {
      const response = await apiClientes.delete(
        `/clientes-api/v1/admin-management/users/` + usuario.id,
        {}
      );
      if (response.status == 202) {
        $q.notify({
          type: 'positive',
          message: `Usuário ${usuario.username} removido com sucesso.`,
        });
      }
    } catch (e) {
      console.error(e);
      $q.notify({ type: 'negative', message: 'Erro ao remover usuário.' });
    } finally {
      fetchApi(props);
    }
  };
</script>

// frontend/admin/src/pages/configuracoes/AdministradoresPage.tsx
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { Box, Typography, IconButton, Menu, MenuItem } from '@mui/material'
import MoreVertIcon from '@mui/icons-material/MoreVert'
import DeleteIcon from '@mui/icons-material/Delete'
import { useSnackbar } from 'notistack'
import { apiClientes } from '../../api/axios'
import { ServerTable, type ColumnDef, type PaginationState } from '../../components/ServerTable'

type Usuario = Record<string, unknown>

export default function AdministradoresPage() {
  const navigate = useNavigate()
  const { enqueueSnackbar } = useSnackbar()
  const [usuarios, setUsuarios] = useState<Usuario[]>([])
  const [loading, setLoading] = useState(false)
  const [pagination, setPagination] = useState<PaginationState>({ page: 1, rowsPerPage: 10, rowsNumber: 0 })
  const [menuAnchor, setMenuAnchor] = useState<{ el: HTMLElement; row: Usuario } | null>(null)

  const columns: ColumnDef[] = [
    { field: 'name', headerName: 'Nome', sortable: false },
    { field: 'username', headerName: 'Username', sortable: false },
    { field: 'loginMethod', headerName: 'Método de Login', sortable: false },
    { field: 'enabled', headerName: 'Habilitado', sortable: false, renderCell: row => row.enabled ? 'Sim' : 'Não' },
    {
      field: 'actions',
      headerName: 'Ações',
      sortable: false,
      align: 'center',
      renderCell: row => (
        <IconButton
          size="small"
          onClick={e => { e.stopPropagation(); setMenuAnchor({ el: e.currentTarget, row: row as Usuario }) }}
        >
          <MoreVertIcon fontSize="small" />
        </IconButton>
      ),
    },
  ]

  const fetchUsuarios = async (pag: PaginationState) => {
    setLoading(true)
    try {
      const resp = await apiClientes.get(
        `/clientes-api/v1/admin-management/users?page=${pag.page}&size=${pag.rowsPerPage}`
      )
      setUsuarios(resp.data.content ?? [])
      setPagination(p => ({ ...p, rowsNumber: resp.data.totalElements ?? 0 }))
    } catch (error: unknown) {
      if ((error as { response?: { status: number } }).response?.status === 403) navigate('/admin')
      else enqueueSnackbar('Erro ao buscar administradores.', { variant: 'error' })
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { fetchUsuarios(pagination) }, [pagination.page, pagination.rowsPerPage])

  async function removerUsuario(usuario: Usuario) {
    try {
      const resp = await apiClientes.delete(`/clientes-api/v1/admin-management/users/${usuario.id}`)
      if (resp.status === 202)
        enqueueSnackbar(`Usuário ${usuario.username} removido com sucesso.`, { variant: 'success' })
    } catch {
      enqueueSnackbar('Erro ao remover usuário.', { variant: 'error' })
    } finally {
      setMenuAnchor(null)
      fetchUsuarios(pagination)
    }
  }

  return (
    <Box>
      <Typography variant="h4" sx={{ mb: 2 }}>Administradores</Typography>

      <ServerTable
        rows={usuarios}
        columns={columns}
        loading={loading}
        pagination={pagination}
        onPaginationChange={setPagination}
        noDataLabel="Nenhum usuário encontrado."
      />

      <Menu anchorEl={menuAnchor?.el} open={!!menuAnchor} onClose={() => setMenuAnchor(null)}>
        <MenuItem onClick={() => menuAnchor && removerUsuario(menuAnchor.row)}>
          <DeleteIcon fontSize="small" sx={{ mr: 1, color: 'primary.main' }} />
          Remover Usuário
        </MenuItem>
      </Menu>
    </Box>
  )
}
