// frontend/admin/src/components/ContratoDetalhesCard.vue
<template>
  <q-card v-if="contrato" flat bordered class="q-pa-md">
    <q-card-section class="q-pb-none">
      <div class="text-h6">Detalhes do Contrato</div>
      <div class="text-caption text-grey-7">Informações principais e financeiras</div>
    </q-card-section>

    <q-separator spaced />

    <q-card-section class="q-pt-none">
      <div class="row q-col-gutter-md">
        <div v-for="f in visibleFields" :key="f.label" class="col-12 col-sm-6 col-lg-4">
          <q-card flat class="q-pa-sm bg-grey-1 rounded-borders">
            <div class="text-caption text-grey-7 q-mb-xs">{{ f.label }}</div>
            <div class="row items-center no-wrap">
              <div class="col text-body2 text-weight-medium ellipsis">
                {{ formatValue(f) }}
              </div>
              <q-btn
                size="sm"
                dense
                round
                flat
                icon="content_copy"
                :title="`Copiar ${f.label}`"
                @click="copy(formatValue(f))"
              >
                <q-tooltip>Clicar para copiar</q-tooltip>
              </q-btn>
            </div>
          </q-card>
        </div>
      </div>
    </q-card-section>
  </q-card>
</template>

<script setup lang="ts">
  import { computed } from 'vue';
  import { useQuasar } from 'quasar';

  type Contrato = Record<string, any>;

  const props = defineProps<{ contrato: Contrato | null }>();

  const $q = useQuasar();

  /**
   * No FIELD_MAP você pode usar:
   * - key: 'campo' (string única)
   * - keys: ['alias1', 'alias2'] (primeiro valor não vazio será usado)
   * - type:  'currency' | 'number' | 'percent' | 'boolean'
   */
  type Field =
    | {
        label: string;
        key: string;
        type?: 'currency' | 'number' | 'percent' | 'boolean';
      }
    | {
        label: string;
        keys: string[];
        type?: 'currency' | 'number' | 'percent' | 'boolean';
      };

  const FIELD_MAP: Field[] = [
    // Identificação
    { label: 'Número Contrato', key: 'numeContrato' },
    { label: 'Empresa', key: 'empresa' },
    { label: 'Nome da Empresa', key: 'nomeEmpresa' },
    { label: 'CNPJ Empresa', key: 'cnpjEmpresa' },
    { label: 'Cidade Empresa', key: 'cidadeEmpresa' },
    { label: 'Endereço Empresa', key: 'enderecoCompletoEmpresa' },

    // Cliente
    { label: 'Cliente', key: 'cliente' },
    { label: 'Nome Cliente', key: 'nomeCliente' },
    { label: 'CPF/CIC Cliente', key: 'cic' },
    { label: 'RG Cliente', key: 'rgCliente' },
    { label: 'Data Nascimento Cliente', key: 'clienteNascimento' },
    { label: 'Endereço Cliente', key: 'enderecoCompletoCliente' },
    { label: 'Cidade Cliente', key: 'cidade' },
    { label: 'Estado Cliente', key: 'estado' },
    { label: 'CEP Cliente', key: 'cepCompleto' },
    { label: 'Telefones Cliente', key: 'telefones' },

    // Contrato
    { label: 'Contrato Original', key: 'numeContratoOriginal' },
    { label: 'Contrato Anterior', key: 'numeContratoAnterior' },
    { label: 'Número Contrato Matriz', key: 'numeroContratoMatriz' },
    { label: 'Número Contrato Interno', key: 'numeroContratoInterno' },
    { label: 'Observação Contrato', key: 'observacaoContrato' },

    // Financeiro
    { label: 'Valor Contrato', key: 'valorContrato' },
    { label: 'Valor Contrato Extenso', key: 'valorContratoExtenso' },
    { label: 'Receita', key: 'receita' },
    { label: 'Denominação', key: 'denominacao' },
    { label: 'Total Saldo em Aberto', key: 'totalSaldoEmAberto' },

    // Unidade de Custo
    { label: 'Centro de Custo', key: 'ccusto' },
    { label: 'Nome Centro de Custo', key: 'nomeCcusto' },
    { label: 'Unidade de Custo', key: 'unidadeDeCusto' },
    { label: 'Unidade de Custo Original', key: 'unidadeDeCustoOriginal' },
    { label: 'Quadra Original', key: 'quadraOriginal' },
    { label: 'Lote Original', key: 'loteOriginal' },

    // Datas principais
    { label: 'Data Base', key: 'dataBase' },
    { label: 'Data Emissão', key: 'dtEmissao' },
    { label: 'Data Inclusão', key: 'dataInclusao' },
    { label: 'Data Rescisão', key: 'dataRescisao' },
    { label: 'Data Entrega Unidade', key: 'dataEntregaUnidade' },

    // Corretor/Vendedor
    { label: 'Nome Corretor', key: 'nomeCorretor' },
    { label: 'Nome Vendedor', key: 'nomeVendedor' },

    // Conjuge
    { label: 'Nome Cônjuge', key: 'conjugueNome' },
    { label: 'CPF Cônjuge', key: 'cpfConjugue' },

    // Diversos
    { label: 'Descrição', key: 'descricao' },
    { label: 'Tipo Documento', key: 'tipoDoc' },
    { label: 'Tipo Unidade', key: 'tipoUnidade' },
    { label: 'Unidade/Quadra/Lote', key: 'unidadeQuadraLote' },
    { label: 'Usuário Inclusão', key: 'usuarioInclusao' },
    { label: 'Observação Cadastro Cliente', key: 'observacaoCadastroCliente' },
    { label: 'ID', key: 'id' },
  ];

  /** —— Helpers de valor/visibilidade —— */
  function firstNonEmpty(...vals: any[]) {
    for (const v of vals) {
      if (v !== undefined && v !== null && String(v) !== '') return v;
    }
    return undefined;
  }

  function getRawValue(f: Field) {
    if ('key' in f) return props.contrato?.[f.key];
    return firstNonEmpty(...f.keys.map((k) => props.contrato?.[k]));
  }

  const visibleFields = computed(() => FIELD_MAP.filter((f) => getRawValue(f) !== undefined));

  /** —— Formatação —— */
  const numberFmt = new Intl.NumberFormat('pt-BR');

  function formatValue(f: Field) {
    const v: any = getRawValue(f);
    switch (f.type) {
      case 'number':
        return isFinite(+v) ? numberFmt.format(+v) : v != null ? String(v) : '';
      case 'percent':
        return isFinite(+v) ? `${numberFmt.format(+v)}%` : v != null ? String(v) : '';
      case 'boolean':
        return v ? 'Sim' : 'Não';
      default:
        return v != null ? String(v) : '';
    }
  }

  /** —— UX —— */
  function copy(text: string) {
    navigator.clipboard.writeText(text);
    $q.notify({ message: 'Copiado!', color: 'positive', icon: 'check', timeout: 1200 });
  }
</script>

<style scoped>
  .rounded-borders {
    border-radius: 12px;
  }
  .ellipsis {
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
</style>

// frontend/admin/src/components/ContratoDetalhesCard.tsx
import { Box, Card, CardContent, Divider, Grid, IconButton, Tooltip, Typography } from '@mui/material'
import ContentCopyIcon from '@mui/icons-material/ContentCopy'
import { useSnackbar } from 'notistack'
import { useMemo } from 'react'

type Contrato = Record<string, unknown>

type Field =
  | { label: string; key: string; type?: 'currency' | 'number' | 'percent' | 'boolean' }
  | { label: string; keys: string[]; type?: 'currency' | 'number' | 'percent' | 'boolean' }

const FIELD_MAP: Field[] = [
  { label: 'Número Contrato', key: 'numeContrato' },
  { label: 'Empresa', key: 'empresa' },
  { label: 'Nome da Empresa', key: 'nomeEmpresa' },
  { label: 'CNPJ Empresa', key: 'cnpjEmpresa' },
  { label: 'Cidade Empresa', key: 'cidadeEmpresa' },
  { label: 'Endereço Empresa', key: 'enderecoCompletoEmpresa' },
  { label: 'Cliente', key: 'cliente' },
  { label: 'Nome Cliente', key: 'nomeCliente' },
  { label: 'CPF/CIC Cliente', key: 'cic' },
  { label: 'RG Cliente', key: 'rgCliente' },
  { label: 'Data Nascimento Cliente', key: 'clienteNascimento' },
  { label: 'Endereço Cliente', key: 'enderecoCompletoCliente' },
  { label: 'Cidade Cliente', key: 'cidade' },
  { label: 'Estado Cliente', key: 'estado' },
  { label: 'CEP Cliente', key: 'cepCompleto' },
  { label: 'Telefones Cliente', key: 'telefones' },
  { label: 'Contrato Original', key: 'numeContratoOriginal' },
  { label: 'Contrato Anterior', key: 'numeContratoAnterior' },
  { label: 'Número Contrato Matriz', key: 'numeroContratoMatriz' },
  { label: 'Número Contrato Interno', key: 'numeroContratoInterno' },
  { label: 'Observação Contrato', key: 'observacaoContrato' },
  { label: 'Valor Contrato', key: 'valorContrato' },
  { label: 'Valor Contrato Extenso', key: 'valorContratoExtenso' },
  { label: 'Receita', key: 'receita' },
  { label: 'Denominação', key: 'denominacao' },
  { label: 'Total Saldo em Aberto', key: 'totalSaldoEmAberto' },
  { label: 'Centro de Custo', key: 'ccusto' },
  { label: 'Nome Centro de Custo', key: 'nomeCcusto' },
  { label: 'Unidade de Custo', key: 'unidadeDeCusto' },
  { label: 'Unidade de Custo Original', key: 'unidadeDeCustoOriginal' },
  { label: 'Quadra Original', key: 'quadraOriginal' },
  { label: 'Lote Original', key: 'loteOriginal' },
  { label: 'Data Base', key: 'dataBase' },
  { label: 'Data Emissão', key: 'dtEmissao' },
  { label: 'Data Inclusão', key: 'dataInclusao' },
  { label: 'Data Rescisão', key: 'dataRescisao' },
  { label: 'Data Entrega Unidade', key: 'dataEntregaUnidade' },
  { label: 'Nome Corretor', key: 'nomeCorretor' },
  { label: 'Nome Vendedor', key: 'nomeVendedor' },
  { label: 'Nome Cônjuge', key: 'conjugueNome' },
  { label: 'CPF Cônjuge', key: 'cpfConjugue' },
  { label: 'Descrição', key: 'descricao' },
  { label: 'Tipo Documento', key: 'tipoDoc' },
  { label: 'Tipo Unidade', key: 'tipoUnidade' },
  { label: 'Unidade/Quadra/Lote', key: 'unidadeQuadraLote' },
  { label: 'Usuário Inclusão', key: 'usuarioInclusao' },
  { label: 'Observação Cadastro Cliente', key: 'observacaoCadastroCliente' },
  { label: 'ID', key: 'id' },
]

const numberFmt = new Intl.NumberFormat('pt-BR')

function firstNonEmpty(...vals: unknown[]) {
  for (const v of vals) {
    if (v !== undefined && v !== null && String(v) !== '') return v
  }
  return undefined
}

function getRawValue(f: Field, contrato: Contrato) {
  if ('key' in f) return contrato[f.key]
  return firstNonEmpty(...f.keys.map(k => contrato[k]))
}

function formatValue(f: Field, contrato: Contrato): string {
  const v = getRawValue(f, contrato)
  switch (f.type) {
    case 'number':
      return isFinite(+(v as number)) ? numberFmt.format(+(v as number)) : v != null ? String(v) : ''
    case 'percent':
      return isFinite(+(v as number))
        ? `${numberFmt.format(+(v as number))}%`
        : v != null
          ? String(v)
          : ''
    case 'boolean':
      return v ? 'Sim' : 'Não'
    default:
      return v != null ? String(v) : ''
  }
}

export function ContratoDetalhesCard({ contrato }: { contrato: Contrato | null }) {
  const { enqueueSnackbar } = useSnackbar()

  const visibleFields = useMemo(
    () => (contrato ? FIELD_MAP.filter(f => getRawValue(f, contrato) !== undefined) : []),
    [contrato],
  )

  function copy(text: string) {
    navigator.clipboard.writeText(text)
    enqueueSnackbar('Copiado!', { variant: 'success', autoHideDuration: 1200 })
  }

  if (!contrato) return null

  return (
    <Card variant="outlined">
      <CardContent>
        <Typography variant="h6">Detalhes do Contrato</Typography>
        <Typography variant="caption" color="text.secondary">
          Informações principais e financeiras
        </Typography>
        <Divider sx={{ my: 2 }} />
        <Grid container spacing={2}>
          {visibleFields.map(f => {
            const text = formatValue(f, contrato)
            return (
              <Grid item xs={12} sm={6} lg={4} key={f.label}>
                <Box sx={{ bgcolor: 'grey.50', borderRadius: 2, p: 1 }}>
                  <Typography variant="caption" color="text.secondary" display="block">
                    {f.label}
                  </Typography>
                  <Box sx={{ display: 'flex', alignItems: 'center' }}>
                    <Typography
                      variant="body2"
                      fontWeight={500}
                      sx={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}
                    >
                      {text}
                    </Typography>
                    <Tooltip title="Clicar para copiar">
                      <IconButton size="small" onClick={() => copy(text)}>
                        <ContentCopyIcon fontSize="inherit" />
                      </IconButton>
                    </Tooltip>
                  </Box>
                </Box>
              </Grid>
            )
          })}
        </Grid>
      </CardContent>
    </Card>
  )
}
