// frontend/admin/src/pages/forgot-password/ForgotPasswordPage.tsx
import { useState, useRef, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Box,
  Card,
  CardContent,
  CardActions,
  TextField,
  Button,
  Typography,
  Alert,
  Stepper,
  Step,
  StepLabel,
  Collapse,
  InputAdornment,
  IconButton,
} from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import HelpIcon from '@mui/icons-material/Help'
import VisibilityIcon from '@mui/icons-material/Visibility'
import VisibilityOffIcon from '@mui/icons-material/VisibilityOff'
import type { AxiosError } from 'axios'
import { apiClientes } from '../../api/axios'

interface ErrorPayload {
  code?: string
  message?: string
  seconds?: number
  otpTokenValid?: boolean
}

type AlertData = { type: 'info' | 'success' | 'error'; message: string } | null

export default function ForgotPasswordPage() {
  const navigate = useNavigate()
  const [activeStep, setActiveStep] = useState(0)
  const [username, setUsername] = useState('')
  const [otp, setOtp] = useState('')
  const [password, setPassword] = useState('')
  const [passwordConfirm, setPasswordConfirm] = useState('')
  const [showPwd, setShowPwd] = useState(false)
  const [showPwdConfirm, setShowPwdConfirm] = useState(false)
  const [loading, setLoading] = useState({ request: false, reset: false })
  const [cooldown, setCooldown] = useState(0)
  const [alert, setAlert] = useState<AlertData>(null)
  const [showHelp, setShowHelp] = useState(false)
  const cooldownRef = useRef<number | null>(null)

  useEffect(() => {
    return () => { if (cooldownRef.current) clearInterval(cooldownRef.current) }
  }, [])

  function startCooldown(secs = 60) {
    setCooldown(secs)
    if (cooldownRef.current) clearInterval(cooldownRef.current)
    cooldownRef.current = window.setInterval(() => {
      setCooldown(prev => {
        if (prev <= 1) {
          clearInterval(cooldownRef.current!)
          cooldownRef.current = null
          return 0
        }
        return prev - 1
      })
    }, 1000)
  }

  async function requestReset(isResend = false) {
    if (!username.trim()) return
    setLoading(l => ({ ...l, request: true }))
    setAlert(null)
    try {
      await apiClientes.post('/clientes-api/v1/password-reset', { username: username.trim() })
      setAlert({
        type: 'info',
        message: isResend
          ? 'Se possível, reenviamos um novo código. Verifique SMS/E-mail.'
          : 'Se o usuário existir e tiver contato válido, você receberá um código por SMS/E-mail.',
      })
      setActiveStep(1)
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>
      if (e.response?.status === 429) {
        const secs = e.response.data?.seconds ?? 60
        setAlert({ type: 'error', message: e.response.data?.message ?? `Muitas tentativas. Aguarde ${secs}s.` })
        startCooldown(secs)
      } else {
        setAlert({ type: 'error', message: e.response?.data?.message ?? 'Não foi possível iniciar a recuperação.' })
      }
    } finally {
      setLoading(l => ({ ...l, request: false }))
    }
  }

  async function resetPassword() {
    if (!otp.trim() || !password.trim() || password !== passwordConfirm) return
    setLoading(l => ({ ...l, reset: true }))
    setAlert(null)
    try {
      await apiClientes.post('/clientes-api/v1/password-reset/reset', {
        username: username.trim(),
        token: otp.trim(),
        password,
      })
      setAlert({ type: 'success', message: 'Senha alterada com sucesso. Redirecionando para o login...' })
      setTimeout(() => navigate('/admin'), 700)
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>
      const msg = e.response?.data?.message ?? 'Falha ao redefinir a senha.'
      if (e.response?.status === 400) {
        if (e.response.data?.otpTokenValid === false) {
          setAlert({ type: 'error', message: `${msg} — Solicite um novo código.` })
          setOtp('')
          setActiveStep(0)
          startCooldown(30)
        } else {
          setAlert({ type: 'error', message: msg })
        }
      } else if (e.response?.status === 401) {
        setAlert({ type: 'error', message: msg })
        setOtp('')
        setActiveStep(0)
      } else if (e.response?.status === 429) {
        const secs = e.response.data?.seconds ?? 60
        setAlert({ type: 'error', message: msg })
        startCooldown(secs)
      } else {
        setAlert({ type: 'error', message: msg })
      }
    } finally {
      setLoading(l => ({ ...l, reset: false }))
    }
  }

  return (
    <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '80vh', px: 2 }}>
      <Card sx={{ maxWidth: 520, width: '100%' }}>
        <CardContent>
          <Typography variant="h6" align="center">Esqueci minha senha</Typography>
          <Typography variant="subtitle2" align="center" color="text.secondary" sx={{ mb: 2 }}>
            Redefina sua senha em dois passos
          </Typography>

          {alert && <Alert severity={alert.type} sx={{ mb: 2 }}>{alert.message}</Alert>}

          <Stepper activeStep={activeStep} sx={{ mb: 3 }}>
            <Step><StepLabel>Identificar usuário</StepLabel></Step>
            <Step><StepLabel>Validar código e redefinir</StepLabel></Step>
          </Stepper>

          {activeStep === 0 && (
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              <TextField
                label="Usuário"
                value={username}
                onChange={e => setUsername(e.target.value)}
                size="small"
                fullWidth
                disabled={loading.request}
              />
              <Button
                variant="contained"
                disabled={!username.trim() || loading.request || cooldown > 0}
                loading={loading.request}
                onClick={() => requestReset()}
              >
                {cooldown > 0 ? `Enviar código (${cooldown}s)` : 'Enviar código'}
              </Button>
            </Box>
          )}

          {activeStep === 1 && (
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              <Typography variant="caption" color="text.secondary">
                Usuário: <strong>{username}</strong>{' '}
                <Button size="small" onClick={() => setActiveStep(0)}>trocar</Button>
              </Typography>

              <TextField
                label="Código (OTP)"
                value={otp}
                onChange={e => setOtp(e.target.value)}
                size="small"
                fullWidth
                inputProps={{ maxLength: 10, inputMode: 'numeric' }}
                disabled={loading.reset}
              />

              <TextField
                label="Nova senha"
                type={showPwd ? 'text' : 'password'}
                value={password}
                onChange={e => setPassword(e.target.value)}
                size="small"
                fullWidth
                disabled={loading.reset}
                InputProps={{
                  endAdornment: (
                    <InputAdornment position="end">
                      <IconButton size="small" onClick={() => setShowPwd(p => !p)}>
                        {showPwd ? <VisibilityOffIcon /> : <VisibilityIcon />}
                      </IconButton>
                    </InputAdornment>
                  ),
                }}
              />

              <TextField
                label="Confirmar nova senha"
                type={showPwdConfirm ? 'text' : 'password'}
                value={passwordConfirm}
                onChange={e => setPasswordConfirm(e.target.value)}
                size="small"
                fullWidth
                disabled={loading.reset}
                error={passwordConfirm !== '' && password !== passwordConfirm}
                helperText={passwordConfirm !== '' && password !== passwordConfirm ? 'As senhas não conferem' : ''}
                InputProps={{
                  endAdornment: (
                    <InputAdornment position="end">
                      <IconButton size="small" onClick={() => setShowPwdConfirm(p => !p)}>
                        {showPwdConfirm ? <VisibilityOffIcon /> : <VisibilityIcon />}
                      </IconButton>
                    </InputAdornment>
                  ),
                }}
              />

              <Box sx={{ display: 'flex', gap: 1 }}>
                <Button
                  variant="contained"
                  color="secondary"
                  disabled={!otp.trim() || !password.trim() || password !== passwordConfirm || loading.reset}
                  loading={loading.reset}
                  onClick={resetPassword}
                  sx={{ flex: 1 }}
                >
                  Validar e redefinir
                </Button>
                <Button
                  variant="outlined"
                  disabled={cooldown > 0 || loading.request}
                  onClick={() => requestReset(true)}
                  sx={{ flex: 1 }}
                >
                  {cooldown > 0 ? `Reenviar (${cooldown}s)` : 'Reenviar código'}
                </Button>
              </Box>
            </Box>
          )}
        </CardContent>

        <CardActions sx={{ justifyContent: 'space-between' }}>
          <Button startIcon={<ArrowBackIcon />} onClick={() => navigate('/admin')} size="small">
            Voltar ao login
          </Button>
          <Button startIcon={<HelpIcon />} onClick={() => setShowHelp(h => !h)} size="small">
            Ajuda
          </Button>
        </CardActions>

        <Collapse in={showHelp}>
          <Box sx={{ px: 2, pb: 2 }}>
            <Typography variant="caption" color="text.secondary">
              • Se o usuário existir e tiver contato válido, você receberá um OTP por SMS/E-mail.<br />
              • Tente novamente após o cooldown se precisar reenviar.<br />
              • Se o token esgotar as tentativas, solicite um novo envio.
            </Typography>
          </Box>
        </Collapse>
      </Card>
    </Box>
  )
}

// frontend/admin/src/pages/forgot-password/ForgotPasswordPage.vue
<template>
  <div class="q-pa-md flex flex-center" style="min-height: 80vh">
    <q-card class="q-pa-md" style="max-width: 520px; width: 100%">
      <q-card-section class="text-center">
        <div class="text-h6">Esqueci minha senha</div>
        <div class="text-subtitle2 text-grey-7">Redefina sua senha em dois passos</div>
      </q-card-section>

      <q-card-section v-if="alert.message">
        <q-banner
          :class="
            alert.type === 'error'
              ? 'bg-negative text-white'
              : alert.type === 'success'
                ? 'bg-positive text-white'
                : 'bg-grey-3'
          "
          rounded
          dense
        >
          <div class="row items-center no-wrap">
            <q-icon :name="alertIcon" class="q-mr-sm" />
            <div class="col">{{ alert.message }}</div>
          </div>
        </q-banner>
      </q-card-section>

      <q-stepper v-model="step" animated flat header-nav>
        <!-- PASSO 1: Solicitar código -->
        <q-step name="request" title="Identificar usuário" icon="person" :done="step !== 'request'">
          <q-form @submit.prevent="requestReset()">
            <q-input
              v-model="username"
              label="Usuário"
              outlined
              dense
              :disable="loading.request || step !== 'request'"
              :rules="[validaUsername]"
            >
              <template #prepend><q-icon name="person" /></template>
            </q-input>

            <q-btn
              label="Enviar código"
              color="primary"
              class="full-width q-mt-md"
              type="submit"
              :loading="loading.request"
              :disable="!isUsernameReady || loading.request || cooldownSeconds > 0"
            />

            <div class="text-caption text-grey-7 q-mt-sm" v-if="cooldownSeconds > 0">
              Aguarde {{ cooldownSeconds }}s para reenviar.
            </div>
          </q-form>
        </q-step>

        <!-- PASSO 2: Validar OTP e redefinir senha -->
        <q-step name="reset" title="Validar código e redefinir" icon="vpn_key">
          <div class="text-caption text-grey-7 q-mb-sm">
            Usuário: <b>{{ username }}</b>
            <q-btn flat dense size="sm" class="q-ml-xs" label="trocar" @click="step = 'request'" />
          </div>

          <q-form @submit.prevent="resetPassword">
            <q-input
              v-model="otp"
              label="Código (OTP)"
              outlined
              dense
              inputmode="numeric"
              maxlength="10"
              :disable="loading.reset"
              :rules="[validaOtp]"
            >
              <template #prepend><q-icon name="confirmation_number" /></template>
            </q-input>

            <q-input
              v-model="password"
              :type="showPwd ? 'text' : 'password'"
              label="Nova senha"
              outlined
              dense
              :disable="loading.reset"
              :rules="[validaPassword]"
              class="q-mt-sm"
            >
              <template #prepend><q-icon name="lock" /></template>
              <template #append>
                <q-icon
                  :name="showPwd ? 'visibility_off' : 'visibility'"
                  class="cursor-pointer"
                  @click="showPwd = !showPwd"
                />
              </template>
            </q-input>

            <q-input
              v-model="passwordConfirm"
              :type="showPwdConfirm ? 'text' : 'password'"
              label="Confirmar nova senha"
              outlined
              dense
              :disable="loading.reset"
              :rules="[validaPasswordConfirm]"
              class="q-mt-sm"
            >
              <template #prepend><q-icon name="lock" /></template>
              <template #append>
                <q-icon
                  :name="showPwdConfirm ? 'visibility_off' : 'visibility'"
                  class="cursor-pointer"
                  @click="showPwdConfirm = !showPwdConfirm"
                />
              </template>
            </q-input>

            <div class="row q-col-gutter-sm q-mt-md">
              <div class="col-12 col-sm-6">
                <q-btn
                  label="Validar e redefinir"
                  color="secondary"
                  class="full-width"
                  type="submit"
                  :loading="loading.reset"
                  :disable="!isResetFormReady || loading.reset"
                />
              </div>
              <div class="col-12 col-sm-6">
                <q-btn
                  outline
                  color="primary"
                  class="full-width"
                  :label="
                    cooldownSeconds > 0 ? `Reenviar (${cooldownSeconds}s)` : 'Reenviar código'
                  "
                  :disable="cooldownSeconds > 0 || loading.request"
                  @click="requestReset(true)"
                />
              </div>
            </div>
          </q-form>
        </q-step>
      </q-stepper>

      <q-card-actions align="between" class="q-mt-md">
        <q-btn flat icon="arrow_back" label="Voltar ao login" @click="router.push('/login')" />
        <q-btn flat icon="help" label="Ajuda" @click="showHelp = !showHelp" />
      </q-card-actions>

      <q-slide-transition>
        <div v-show="showHelp" class="q-pa-md text-caption text-grey-7">
          • Se o usuário existir e tiver contato válido, você receberá um OTP por SMS/E-mail.<br />
          • Tente novamente após o cooldown se precisar reenviar.<br />
          • Se o token esgotar as tentativas, solicite um novo envio.
        </div>
      </q-slide-transition>
    </q-card>
  </div>
</template>

<script setup lang="ts">
  import { ref, computed, onBeforeUnmount } from 'vue';
  import { useRouter } from 'vue-router';
  import type { AxiosError } from 'axios';
  import { apiClientes } from 'src/boot/axios';

  interface ErrorPayload {
    code?: string; // "429 TOO_MANY_REQUESTS" | "401 UNAUTHORIZED" | "400 BAD_REQUEST" | ...
    message?: string; // mensagens do backend
    seconds?: number; // segundos para expiracao
    otpTokenValid?: boolean; // presente em 400 BAD_REQUEST no reset
  }

  const router = useRouter();

  const step = ref<'request' | 'reset'>('request');

  const username = ref('');
  const otp = ref('');
  const password = ref('');
  const passwordConfirm = ref('');

  const showHelp = ref(false);

  const showPwd = ref(false);
  const showPwdConfirm = ref(false);

  const loading = ref({ request: false, reset: false });

  const alert = ref<{ type: 'info' | 'success' | 'error' | null; message: string }>({
    type: null,
    message: '',
  });
  const alertIcon = computed(() =>
    alert.value.type === 'error'
      ? 'error'
      : alert.value.type === 'success'
        ? 'check_circle'
        : 'info'
  );

  const cooldownSeconds = ref(0);
  let cooldownTimer: number | null = null;

  function setAlert(type: 'info' | 'success' | 'error', message: string) {
    alert.value = { type, message };
  }
  function clearAlert() {
    alert.value = { type: null, message: '' };
  }

  const validaUsername = (v: string) => !!v?.trim() || 'Informe o usuário';
  const validaOtp = (v: string) => !!v?.trim() || 'Informe o código (OTP)';
  const validaPassword = (v: string) => !!v?.trim() || 'Informe a nova senha';
  const validaPasswordConfirm = (v: string) => v === password.value || 'As senhas não conferem';

  const isUsernameReady = computed(() => !!username.value.trim());
  const isResetFormReady = computed(
    () => !!otp.value.trim() && !!password.value.trim() && passwordConfirm.value === password.value
  );

  function startCooldown(seconds = 60) {
    cooldownSeconds.value = seconds;
    if (cooldownTimer) window.clearInterval(cooldownTimer);
    cooldownTimer = window.setInterval(() => {
      if (cooldownSeconds.value <= 1) {
        window.clearInterval(cooldownTimer!);
        cooldownTimer = null;
        cooldownSeconds.value = 0;
      } else {
        cooldownSeconds.value -= 1;
      }
    }, 1000);
  }

  /** Passo 1: solicitar envio do OTP (ou reenviar) */
  async function requestReset(isResend = false) {
    if (!isUsernameReady.value) return;
    loading.value.request = true;
    clearAlert();
    try {
      await apiClientes.post('/clientes-api/v1/password-reset', {
        username: username.value.trim(),
      });
      // Sempre 200: não revelar existência do usuário
      setAlert(
        'info',
        isResend
          ? 'Se possível, reenviamos um novo código. Verifique SMS/E-mail.'
          : 'Se o usuário existir e tiver contato válido, você receberá um código por SMS/E-mail.'
      );
      step.value = 'reset';
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>;
      if (e.response?.status === 429) {
        const secs = e.response.data?.seconds ?? 60;
        setAlert('error', e.response.data?.message || `Muitas tentativas. Aguarde ${secs}s.`);
        startCooldown(secs);
      } else {
        setAlert(
          'error',
          e.response?.data?.message || 'Não foi possível iniciar a recuperação de senha.'
        );
      }
    } finally {
      loading.value.request = false;
    }
  }

  /** Passo 2: validar OTP e redefinir senha */
  async function resetPassword() {
    if (!isResetFormReady.value) return;
    loading.value.reset = true;
    clearAlert();
    try {
      const url = '/clientes-api/v1/password-reset/reset';
      await apiClientes.post(url, {
        username: username.value.trim(),
        token: otp.value.trim(),
        password: password.value,
      });
      setAlert('success', 'Senha alterada com sucesso. Redirecionando para o login...');
      setTimeout(() => router.push('/login'), 700);
    } catch (err) {
      const e = err as AxiosError<ErrorPayload>;
      const msg = e.response?.data?.message || 'Falha ao redefinir a senha.';

      if (e.response?.status === 400) {
        // Token inválido; verificar flag
        if (e.response.data?.otpTokenValid === false) {
          setAlert('error', `${msg} — Solicite um novo código.`);
          // limpar OTP e voltar para solicitar novo envio
          otp.value = '';
          step.value = 'request';
          startCooldown(30);
        } else {
          setAlert('error', msg); // "Token Inválido. Restam X tentativas"
        }
      } else if (e.response?.status === 401) {
        setAlert('error', msg); // Processo não encontrado -> reiniciar
        otp.value = '';
        step.value = 'request';
      } else if (e.response?.status === 429) {
        const secs = e.response.data?.seconds ?? 60;
        setAlert('error', msg);
        startCooldown(secs);
      } else {
        setAlert('error', msg);
      }
    } finally {
      loading.value.reset = false;
    }
  }

  onBeforeUnmount(() => {
    if (cooldownTimer) {
      window.clearInterval(cooldownTimer);
      cooldownTimer = null;
    }
  });
</script>

<style scoped>
  .full-width {
    width: 100%;
  }
</style>
