// frontend/admin/src/pages/mensageria/EmailsEnviadosPage.vue
<template>
  <div class="q-pa-md">
    <h1 class="q-mt-lg q-mb-md">E-mail's Enviados</h1>

    <!-- Filtros -->
    <q-btn
      color="primary"
      icon="filter_list"
      label="Filtros"
      class="q-mb-md"
      @click="filtrosVisiveis = !filtrosVisiveis"
    />

    <!-- Tabela -->
    <q-table
      :rows="lista"
      :columns="columns"
      row-key="id"
      :loading="loading"
      v-model:pagination="pagination"
      @request="fetchApi"
      no-data-label="Nenhum E-mail encontrado."
    />
  </div>
</template>

<script setup lang="ts">
  import { ref, watch } from 'vue';
  import { useRouter } from 'vue-router';
  import { apiClientes } from 'src/boot/axios';

  // Dados da tabela
  const lista = ref([]);
  const filtrosVisiveis = ref(false);
  const loading = ref(false);
  // Router para redirecionamento
  const router = useRouter();

  const pagination = ref({
    page: 1,
    rowsPerPage: 10,
    rowsNumber: 0,
  });

  // Configuração das colunas
  const columns = [
    { name: 'date', align: 'left' as const, label: 'Data de Criação', field: 'date' },
    { name: 'from', align: 'left' as const, label: 'Remetente', field: 'from' },
    { name: 'deliveredTo', align: 'left' as const, label: 'Destinatário', field: 'deliveredTo' },
    { name: 'subject', align: 'left' as const, label: 'Assunto', field: 'subject' },
    { name: 'messageId', align: 'left' as const, label: 'ID da Mensagem', field: 'messageId' },
    { name: 'templateId', align: 'left' as const, label: 'ID do Template', field: 'templateId' },
    { name: 'statusCode', align: 'left' as const, label: 'Status', field: 'statusCode' },
  ];

  // Busca na API
  const fetchApi = async (props: any) => {
    loading.value = true;
    try {
      if (!props.pagination) pagination.value.rowsPerPage = 10;
      else pagination.value.rowsPerPage = props.pagination.rowsPerPage;

      if (!props.pagination) pagination.value.page = 1;
      else pagination.value.page = props.pagination.page;

      const response = await apiClientes.get(
        `/clientes-api/v1/emails-sent?page=${pagination.value.page}&size=${pagination.value.rowsPerPage}`,
        {
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      lista.value = response.data.content;
      pagination.value.rowsNumber = response.data.totalElements || 0;
    } catch (error: any) {
      if (error.response?.status === 403) {
        router.push('/login');
      } else {
        console.error('Erro ao buscar info:', error);
      }
    } finally {
      loading.value = false;
    }
  };

  // Atualiza a lista ao mudar paginação
  watch(pagination, fetchApi, { immediate: true });
</script>

<style scoped>
  .text-h6 {
    font-size: 1.25rem;
    font-weight: bold;
  }
</style>

// frontend/admin/src/pages/mensageria/EmailsEnviadosPage.tsx
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { Box, Typography, Button } from '@mui/material'
import FilterListIcon from '@mui/icons-material/FilterList'
import { apiClientes } from '../../api/axios'
import { ServerTable, type ColumnDef, type PaginationState } from '../../components/ServerTable'

const columns: ColumnDef[] = [
  { field: 'date', headerName: 'Data de Criação', sortable: false },
  { field: 'from', headerName: 'Remetente', sortable: false },
  { field: 'deliveredTo', headerName: 'Destinatário', sortable: false },
  { field: 'subject', headerName: 'Assunto', sortable: false },
  { field: 'messageId', headerName: 'ID da Mensagem', sortable: false },
  { field: 'templateId', headerName: 'ID do Template', sortable: false },
  { field: 'statusCode', headerName: 'Status', sortable: false },
]

export default function EmailsEnviadosPage() {
  const navigate = useNavigate()
  const [lista, setLista] = useState<Record<string, unknown>[]>([])
  const [loading, setLoading] = useState(false)
  const [pagination, setPagination] = useState<PaginationState>({ page: 1, rowsPerPage: 10, rowsNumber: 0 })

  useEffect(() => {
    const fetch = async () => {
      setLoading(true)
      try {
        const resp = await apiClientes.get(
          `/clientes-api/v1/emails-sent?page=${pagination.page}&size=${pagination.rowsPerPage}`
        )
        setLista(resp.data.content ?? [])
        setPagination(p => ({ ...p, rowsNumber: resp.data.totalElements ?? 0 }))
      } catch (error: unknown) {
        if ((error as { response?: { status: number } }).response?.status === 403) navigate('/admin')
      } finally {
        setLoading(false)
      }
    }
    fetch()
  }, [pagination.page, pagination.rowsPerPage])

  return (
    <Box>
      <Typography variant="h4" sx={{ mb: 2 }}>E-mails Enviados</Typography>
      <Button variant="contained" startIcon={<FilterListIcon />} sx={{ mb: 2 }}>Filtros</Button>
      <ServerTable
        rows={lista}
        columns={columns}
        loading={loading}
        pagination={pagination}
        onPaginationChange={setPagination}
        noDataLabel="Nenhum e-mail encontrado."
      />
    </Box>
  )
}
