// frontend/admin/src/pages/clientes/ClientesPage.tsx
import { useState, useEffect, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import { Box, Typography, Button, Stack } from '@mui/material'
import FilterListIcon from '@mui/icons-material/FilterList'
import DoneAllIcon from '@mui/icons-material/DoneAll'
import ClearIcon from '@mui/icons-material/Clear'
import DownloadIcon from '@mui/icons-material/Download'
import MoreVertIcon from '@mui/icons-material/MoreVert'
import PersonAddIcon from '@mui/icons-material/PersonAdd'
import { Menu, MenuItem, IconButton } from '@mui/material'
import { useSnackbar } from 'notistack'
import { apiClientes } from '../../api/axios'
import { ServerTable, type ColumnDef, type PaginationState } from '../../components/ServerTable'
import { useTriStateMultiSort } from '../../hooks/useTriStateMultiSort'

type ClienteRow = {
  id: string | number
  idErp?: string
  name?: string
  username?: string
  grupoContabil?: string
  loginMethod?: string
  enabled?: boolean
}

const OPERATORS = ['EQUALS', 'CONTAINS', 'STARTS_WITH', 'ENDS_WITH'] as const

export default function ClientesPage() {
  const navigate = useNavigate()
  const { enqueueSnackbar } = useSnackbar()
  const [clientes, setClientes] = useState<ClienteRow[]>([])
  const [loading, setLoading] = useState(false)
  const [pagination, setPagination] = useState<PaginationState>({ page: 1, rowsPerPage: 10, rowsNumber: 0 })
  const [selectedIds, setSelectedIds] = useState<Set<string | number>>(new Set())
  const [menuAnchor, setMenuAnchor] = useState<{ el: HTMLElement; row: ClienteRow } | null>(null)
  const { dirOf, cycleSort, buildSortQuery } = useTriStateMultiSort({
    storageKey: 'clientes:list:sort',
    persist: true,
  })

  const columns: ColumnDef[] = [
    { field: 'idErp', headerName: 'ID Eficaz' },
    { field: 'name', headerName: 'Nome' },
    { field: 'username', headerName: 'CPF/CNPJ' },
    { field: 'grupoContabil', headerName: 'Grupo Contábil' },
    { field: 'loginMethod', headerName: 'Método de Login' },
    {
      field: 'enabled',
      headerName: 'Habilitado',
      renderCell: row => (row.enabled ? 'Sim' : 'Não'),
    },
    {
      field: 'actions',
      headerName: 'Ações',
      sortable: false,
      align: 'center',
      renderCell: row => (
        <IconButton
          size="small"
          onClick={e => {
            e.stopPropagation()
            setMenuAnchor({ el: e.currentTarget, row: row as ClienteRow })
          }}
        >
          <MoreVertIcon fontSize="small" />
        </IconButton>
      ),
    },
  ]

  const fetchClientes = useCallback(
    async (pag: PaginationState) => {
      setLoading(true)
      try {
        const url = `/clientes-api/v1/customers-management/search?page=${pag.page}&size=${pag.rowsPerPage}${buildSortQuery()}`
        const resp = await apiClientes.post(url, {}, { headers: { 'Content-Type': 'application/json' } })
        setClientes(resp.data.content ?? [])
        setPagination(p => ({ ...p, rowsNumber: resp.data.totalElements ?? 0 }))
      } catch (error: unknown) {
        if ((error as { response?: { status: number } }).response?.status === 403) navigate('/admin')
        else enqueueSnackbar('Erro ao buscar clientes.', { variant: 'error' })
      } finally {
        setLoading(false)
      }
    },
    [buildSortQuery, navigate, enqueueSnackbar],
  )

  useEffect(() => {
    fetchClientes(pagination)
  }, [pagination.page, pagination.rowsPerPage])

  function handleSort(field: string) {
    cycleSort(field)
    fetchClientes({ ...pagination, page: 1 })
  }

  function handlePaginationChange(p: PaginationState) {
    setPagination(p)
  }

  function toggleSelect(id: unknown) {
    setSelectedIds(prev => {
      const next = new Set(prev)
      if (next.has(id as string | number)) next.delete(id as string | number)
      else next.add(id as string | number)
      return next
    })
  }

  const allPageSelected = clientes.length > 0 && clientes.every(r => selectedIds.has(r.id))
  const somePageSelected = clientes.some(r => selectedIds.has(r.id))

  function toggleSelectAllPage(val: boolean) {
    setSelectedIds(prev => {
      const next = new Set(prev)
      clientes.forEach(r => (val ? next.add(r.id) : next.delete(r.id)))
      return next
    })
  }

  function downloadBlob(response: { data: BlobPart; headers: Record<string, string> }, fallbackName: string) {
    let nomeArquivo = fallbackName
    const disposition = response.headers['content-disposition']
    if (disposition) {
      const match = disposition.match(/filename="?(.+?)"?$/)
      if (match) nomeArquivo = match[1]!
    }
    const blob = new Blob([response.data], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    })
    const link = document.createElement('a')
    link.href = URL.createObjectURL(blob)
    link.download = nomeArquivo
    link.click()
    URL.revokeObjectURL(link.href)
  }

  async function exportarSelecionados() {
    if (!selectedIds.size) return
    try {
      const resp = await apiClientes.post('/clientes-api/v1/exportar', Array.from(selectedIds), {
        responseType: 'blob',
      })
      downloadBlob(resp as { data: BlobPart; headers: Record<string, string> }, 'Clientes_Exportados.xlsx')
      enqueueSnackbar(`${selectedIds.size} clientes exportados.`, { variant: 'success' })
    } catch {
      enqueueSnackbar('Erro ao exportar.', { variant: 'error' })
    }
  }

  async function adicionarBetaUser(cliente: ClienteRow) {
    try {
      const resp = await apiClientes.post(`/clientes-api/v1/settings/beta-users?userModelId=${cliente.id}`, {})
      if (resp.status === 201)
        enqueueSnackbar(`Cliente ${cliente.name ?? ''} adicionado aos Beta Users.`, { variant: 'success' })
      else if (resp.status === 208)
        enqueueSnackbar(`Cliente ${cliente.name ?? ''} já existente na lista de Beta Users.`, { variant: 'warning' })
    } catch {
      enqueueSnackbar('Erro ao adicionar cliente aos Beta Users.', { variant: 'error' })
    }
    setMenuAnchor(null)
  }

  return (
    <Box>
      <Typography variant="h4" sx={{ mb: 2 }}>
        Clientes
      </Typography>

      <Stack direction="row" spacing={1} sx={{ mb: 2 }} flexWrap="wrap">
        <Button variant="contained" startIcon={<FilterListIcon />}>
          Filtros
        </Button>
        <Box sx={{ flex: 1 }} />
        <Button
          variant="outlined"
          color="error"
          startIcon={<ClearIcon />}
          disabled={selectedIds.size === 0}
          onClick={() => setSelectedIds(new Set())}
        >
          Limpar seleção
        </Button>
        <Button
          variant="outlined"
          startIcon={<DoneAllIcon />}
          disabled={clientes.length === 0}
          onClick={() => toggleSelectAllPage(!allPageSelected)}
        >
          {allPageSelected ? 'Desmarcar todos (página)' : 'Selecionar todos (página)'}
        </Button>
        <Button
          variant="contained"
          color="success"
          startIcon={<DownloadIcon />}
          disabled={selectedIds.size === 0}
          onClick={exportarSelecionados}
        >
          Exportar
        </Button>
      </Stack>

      <ServerTable
        rows={clientes as Record<string, unknown>[]}
        columns={columns}
        loading={loading}
        pagination={pagination}
        onPaginationChange={handlePaginationChange}
        dirOf={dirOf}
        onSort={handleSort}
        selection
        selectedIds={selectedIds as Set<unknown>}
        onToggleSelect={toggleSelect}
        allPageSelected={allPageSelected}
        somePageSelected={somePageSelected}
        onToggleSelectAllPage={toggleSelectAllPage}
        noDataLabel="Nenhum cliente encontrado."
        rowsPerPageOptions={[5, 10, 20, 50, 100]}
      />

      <Menu
        anchorEl={menuAnchor?.el}
        open={!!menuAnchor}
        onClose={() => setMenuAnchor(null)}
      >
        <MenuItem onClick={() => menuAnchor && adicionarBetaUser(menuAnchor.row)}>
          <PersonAddIcon fontSize="small" sx={{ mr: 1, color: 'primary.main' }} />
          Adicionar à lista de Beta Users
        </MenuItem>
      </Menu>
    </Box>
  )
}

// frontend/admin/src/pages/clientes/ClientesPage.vue
<template>
  <q-page class="q-pa-md">
    <h1 class="q-mt-lg q-mb-md">Clientes</h1>

    <!-- Barra de ações -->
    <div class="row items-center q-gutter-sm q-mb-md">
      <q-btn
        color="primary"
        icon="filter_list"
        label="Filtros"
        @click="filtrosVisiveis = !filtrosVisiveis"
      />

      <q-space />

      <q-btn
        outline
        color="negative"
        icon="clear"
        label="Limpar seleção"
        :disable="selectedClientes.length === 0"
        @click="limparSelecao"
      />

      <q-btn
        outline
        color="primary"
        icon="done_all"
        :label="allPageSelected ? 'Desmarcar todos (página)' : 'Selecionar todos (página)'"
        :disable="clientes.length === 0"
        @click="toggleSelectAllPage"
      />

      <q-btn
        color="positive"
        icon="download"
        label="Exportar"
        :disable="selectedClientes.length === 0"
        @click="exportarSelecionados(selectedIds)"
      />
    </div>

    <q-table
      ref="tableRef"
      :rows="clientes"
      :columns="columns"
      row-key="id"
      :loading="loading"
      v-model:pagination="pagination"
      v-model:selected="selectedClientes"
      selection="multiple"
      @request="fetchClientes"
      no-data-label="Nenhum cliente encontrado."
      :rows-per-page-options="[5, 10, 20, 50, 100, 150]"
    >
      <template #header="h">
        <q-tr :props="h">
          <q-th auto-width class="selection-header-th">
            <span class="selection-header-spacer" aria-hidden="true"></span>
          </q-th>

          <q-th
            v-for="col in h.cols"
            :key="col.name"
            :props="h"
            :class="['header-th', col.name !== 'selection' && isSortable(col) && 'cursor-pointer']"
            :aria-sort="
              col.name !== 'selection' && isSortable(col)
                ? dirOf(col.name) === 'asc'
                  ? 'ascending'
                  : dirOf(col.name) === 'desc'
                    ? 'descending'
                    : 'none'
                : 'none'
            "
            @click.stop="col.name !== 'selection' && isSortable(col) && handleCycleSort(col.name)"
          >
            <span class="header-wrap" :class="[`align-${col.align || 'left'}`]">
              <span class="header-label">{{ col.label }}</span>

              <q-icon
                v-if="isSortable(col) && dirOf(col.name) === 'asc'"
                name="arrow_upward"
                class="sort-icon"
                size="16px"
              />
              <q-icon
                v-else-if="isSortable(col) && dirOf(col.name) === 'desc'"
                name="arrow_downward"
                class="sort-icon"
                size="16px"
              />
              <span v-else class="sort-spacer"></span>
            </span>
          </q-th>
        </q-tr>
      </template>

      <!-- ações -->
      <template #body-cell-actions="props">
        <q-td :props="props">
          <q-btn flat round dense icon="more_vert">
            <q-menu>
              <q-list style="min-width: 200px">
                <q-item clickable v-close-popup @click="adicionarBetaUser(props.row)">
                  <q-item-section avatar>
                    <q-icon name="person_add" color="primary" />
                  </q-item-section>
                  <q-item-section>Adicionar à lista de Beta Users</q-item-section>
                </q-item>
              </q-list>
            </q-menu>
          </q-btn>
        </q-td>
      </template>
    </q-table>
  </q-page>
</template>

<script setup lang="ts">
  import { computed, ref, onMounted } from 'vue';
  import { useRouter } from 'vue-router';
  import { useQuasar, type QTableColumn } from 'quasar';
  import { apiClientes } from 'src/boot/axios';
  import { useTriStateMultiSort } from 'src/composables/useTriStateMultiSort';

  const $q = useQuasar();
  const router = useRouter();

  interface Filter {
    key: string;
    value: string;
    operator: string;
  }

  type ClienteRow = {
    id: string | number;
    idErp?: string;
    name?: string;
    username?: string;
    grupoContabil?: string;
    loginMethod?: string;
    enabled?: boolean;
  };

  const tableRef = ref<any>(null);
  const clientes = ref<ClienteRow[]>([]);
  const filtrosVisiveis = ref(false);
  const loading = ref(false);

  const selectedClientes = ref<ClienteRow[]>([]);
  const pagination = ref({ page: 1, rowsPerPage: 10, rowsNumber: 0 });

  /**
   * ✅ Tipagem correta: QTableColumn<ClienteRow>[]
   * field é obrigatório e agora o TS fica feliz.
   */
  const columns: QTableColumn<ClienteRow>[] = [
    {
      name: 'idErp',
      align: 'left',
      label: 'ID Eficaz',
      field: (row) => row.idErp ?? '',
      sortable: true,
    },
    { name: 'name', align: 'left', label: 'Nome', field: (row) => row.name ?? '', sortable: true },
    {
      name: 'username',
      align: 'left',
      label: 'CPF/CNPJ',
      field: (row) => row.username ?? '',
      sortable: true,
    },
    {
      name: 'grupoContabil',
      align: 'left',
      label: 'Grupo Contábil',
      field: (row) => row.grupoContabil ?? '',
      sortable: true,
    },
    {
      name: 'loginMethod',
      align: 'left',
      label: 'Método de Login',
      field: (row) => row.loginMethod ?? '',
      sortable: true,
    },
    {
      name: 'enabled',
      align: 'left',
      label: 'Habilitado',
      field: (row) => (row.enabled ? 'Sim' : 'Não'),
      sortable: true,
    },
    { name: 'actions', align: 'center', label: 'Ações', field: () => '', sortable: false },
  ];

  // helper para saber se coluna é ordenável
  const isSortable = (col: any) => col?.sortable !== false;

  // Ordenação (tri-state multi sort)
  const {
    sortState,
    dirOf,
    cycleSort,
    buildSortQuery,
    init: initSort,
  } = useTriStateMultiSort({
    storageKey: 'clientes:list:sort',
    persist: true,
  });

  function handleCycleSort(field: string) {
    cycleSort(field);
    requestServer();
  }

  function purgeNonSortableFromSort() {
    sortState.value = sortState.value.filter((s: { field: string }) => s.field !== 'actions');
  }

  /** -------- Filtros -------- */
  const filters = ref({ name: '', cpf: '', cnpj: '', idErp: '', email: '' });

  /** -------- Data @request -------- */
  const fetchClientes = async (props?: { pagination: any }) => {
    loading.value = true;
    try {
      const pag = props?.pagination ?? pagination.value;
      const pageParam = pag.page ?? 1; // troque para (pag.page - 1) se backend for 0-based
      const sizeParam = pag.rowsPerPage ?? 10;

      const filterDto: { filters: Filter[]; joinFiltersOperator: string } = {
        filters: [],
        joinFiltersOperator: 'AND',
      };

      if (filters.value.name)
        filterDto.filters.push({ key: 'NAME', value: filters.value.name, operator: 'CONTAINS' });
      if (filters.value.cpf)
        filterDto.filters.push({ key: 'CPF', value: filters.value.cpf, operator: 'EQUALS' });
      if (filters.value.cnpj)
        filterDto.filters.push({ key: 'CNPJ', value: filters.value.cnpj, operator: 'EQUALS' });
      if (filters.value.idErp)
        filterDto.filters.push({ key: 'ID_ERP', value: filters.value.idErp, operator: 'EQUALS' });
      if (filters.value.email)
        filterDto.filters.push({ key: 'EMAIL', value: filters.value.email, operator: 'CONTAINS' });

      const url =
        `/clientes-api/v1/customers-management/search` +
        `?page=${pageParam}&size=${sizeParam}` +
        `${buildSortQuery()}`;

      const resp = await apiClientes.post(
        url,
        { filterDto: filterDto.filters.length ? filterDto : undefined },
        { headers: { 'Content-Type': 'application/json' } }
      );

      const pageData = resp.data;
      clientes.value = pageData.content ?? [];
      pagination.value = { ...pag, rowsNumber: pageData.totalElements ?? 0 };
    } catch (error: any) {
      if (error.response?.status === 403) router.push('/login');
      else {
        console.error('Erro ao buscar clientes:', error);
        $q.notify({ type: 'negative', message: 'Erro ao buscar clientes.' });
      }
    } finally {
      loading.value = false;
    }
  };

  function requestServer() {
    if (tableRef.value?.requestServerInteraction) tableRef.value.requestServerInteraction();
    else fetchClientes({ pagination: pagination.value });
  }

  /** -------- Seleção (apenas página atual) -------- */
  const selectedIds = computed(() => new Set(selectedClientes.value.map((c) => c.id)));

  const allPageSelected = computed(() => {
    if (!clientes.value.length) return false;
    return clientes.value.every((r) => selectedIds.value.has(r.id));
  });

  function toggleSelectAllPage() {
    if (!clientes.value.length) return;

    if (allPageSelected.value) {
      const pageIds = new Set(clientes.value.map((r) => r.id));
      selectedClientes.value = selectedClientes.value.filter((c) => !pageIds.has(c.id));
    } else {
      const map = new Map<ClienteRow['id'], ClienteRow>(
        selectedClientes.value.map((c) => [c.id, c])
      );
      for (const r of clientes.value) map.set(r.id, r);
      selectedClientes.value = Array.from(map.values());
    }
  }

  function limparSelecao() {
    selectedClientes.value = [];
  }

  function downloadBlob(response: any, fallbackName: string) {
    let nomeArquivo = fallbackName;
    const disposition = response.headers['content-disposition'];
    if (disposition) {
      const match = disposition.match(/filename="?(.+?)"?$/);
      if (match) nomeArquivo = match[1];
    }

    const blob = new Blob([response.data], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = nomeArquivo;
    link.click();
    URL.revokeObjectURL(link.href);
  }

  function exportarSelecionados(selectedIds: Set<string | number>) {
    if (!selectedClientes.value.length) return;
    const resp = apiClientes.post(`/clientes-api/v1/exportar`, selectedIds, {
      responseType: 'blob',
    });

    downloadBlob(resp, 'Clientes_Exportados.xlsx');

    $q.notify({
      type: 'positive',
      message: `${selectedClientes.value.length} clientes exportados.`,
    });
  }

  /** -------- Ações -------- */
  const adicionarBetaUser = async (cliente: ClienteRow) => {
    try {
      const response = await apiClientes.post(
        `/clientes-api/v1/settings/beta-users?userModelId=${cliente.id}`,
        {}
      );

      if (response.status === 201) {
        $q.notify({
          type: 'positive',
          message: `Cliente ${cliente.name ?? ''} adicionado aos Beta Users.`,
        });
      } else if (response.status === 208) {
        $q.notify({
          type: 'warning',
          message: `Cliente ${cliente.name ?? ''} já existente na lista de Beta Users.`,
        });
      }
    } catch (e) {
      $q.notify({ type: 'negative', message: 'Erro ao adicionar cliente aos Beta Users.' });
      console.error(e);
    }
  };

  onMounted(() => {
    initSort();
    purgeNonSortableFromSort();
    requestServer();
  });
</script>

<style scoped>
  .q-table thead tr > th {
    white-space: nowrap;
    vertical-align: middle;
  }

  .header-wrap {
    display: inline-flex;
    align-items: center;
    gap: 4px;
    max-width: 100%;
  }

  .header-wrap.align-right {
    justify-content: flex-end;
  }
  .header-wrap.align-center {
    justify-content: center;
  }
  .header-wrap.align-left {
    justify-content: flex-start;
  }

  .header-label {
    display: inline-block;
    max-width: 100%;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .sort-icon,
  .sort-spacer {
    width: 16px;
    height: 16px;
    flex: 0 0 16px;
  }
  .sort-spacer {
    visibility: hidden;
  }

  .header-th:not(.cursor-pointer) {
    cursor: default;
  }

  :deep(.q-table thead tr > th .q-table__sort-icon) {
    display: none !important;
  }
  /* reserva exatamente o espaço visual do checkbox do Quasar (ajustável se necessário) */
  .selection-header-spacer {
    display: inline-block;
    width: 20px;
    height: 20px;
  }
</style>
