// frontend/admin/src/pages/clientes/ContactPreferencesPage.vue
<template>
  <div class="q-pa-md">
    <h1 class="q-mt-lg q-mb-md">Preferencias de Contato</h1>
    <h2 class="text-caption text-grey-7">Importante para processo de Esqueci Minha Senha</h2>

    <!-- Filtros -->
    <q-btn
      color="primary"
      icon="filter_list"
      label="Filtros"
      class="q-mb-md"
      @click="filtrosVisiveis = !filtrosVisiveis"
    />

    <!-- Tabela -->
    <q-table
      :rows="preferencias"
      :columns="columns"
      row-key="id"
      :loading="loading"
      v-model:pagination="pagination"
      @request="fetchApi"
      no-data-label="Nenhuma preferência de contato encontrada."
    />
  </div>
</template>

<script setup lang="ts">
  import { ref, watch } from 'vue';
  import { useRouter } from 'vue-router';
  import { apiClientes } from 'src/boot/axios';

  // Dados da tabela
  const preferencias = ref([]);
  const filtrosVisiveis = ref(false);
  const loading = ref(false);
  // Router para redirecionamento
  const router = useRouter();

  const pagination = ref({
    page: 1,
    rowsPerPage: 10,
    rowsNumber: 0,
  });

  // Configuração das colunas
  const columns = [
    {
      name: 'userFullName',
      align: 'left' as const,
      label: 'Nome do Cliente',
      field: 'userFullName',
    },
    {
      name: 'ownerIdErp',
      align: 'left' as const,
      label: 'ID ERP do Cliente',
      field: 'ownerIdErp',
    },
    { name: 'value', align: 'left' as const, label: 'Contato', field: 'value' },
    { name: 'contactType', align: 'left' as const, label: 'Tipo de Contato', field: 'contactType' },
    { name: 'active', align: 'left' as const, label: 'Ativo?', field: 'active' },
  ];

  // Busca na API
  const fetchApi = async (props: any) => {
    loading.value = true;
    try {
      if (!props.pagination) pagination.value.rowsPerPage = 10;
      else pagination.value.rowsPerPage = props.pagination.rowsPerPage;

      if (!props.pagination) pagination.value.page = 1;
      else pagination.value.page = props.pagination.page;

      const response = await apiClientes.get(
        `/clientes-api/v1/customers-management/contact-preferences/search?page=${pagination.value.page}&size=${pagination.value.rowsPerPage}`,
        {
          headers: {
            'Content-Type': 'application/json',
          },
        }
      );

      preferencias.value = response.data.content;
      pagination.value.rowsNumber = response.data.totalElements || 0;
    } catch (error: any) {
      if (error.response?.status === 403) {
        router.push('/login');
      } else {
        console.error('Erro ao buscar informacoes:', error);
      }
    } finally {
      loading.value = false;
    }
  };
  // Atualiza a lista de resultados ao mudar paginação
  watch(pagination, fetchApi, { immediate: true });
</script>

<style scoped>
  .text-h6 {
    font-size: 1.25rem;
    font-weight: bold;
  }
</style>

// frontend/admin/src/pages/clientes/ContactPreferencesPage.tsx
import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { Box, Typography, Button } from '@mui/material'
import FilterListIcon from '@mui/icons-material/FilterList'
import { apiClientes } from '../../api/axios'
import { ServerTable, type ColumnDef, type PaginationState } from '../../components/ServerTable'

const columns: ColumnDef[] = [
  { field: 'userFullName', headerName: 'Nome do Cliente', sortable: false },
  { field: 'ownerIdErp', headerName: 'ID ERP do Cliente', sortable: false },
  { field: 'value', headerName: 'Contato', sortable: false },
  { field: 'contactType', headerName: 'Tipo de Contato', sortable: false },
  { field: 'active', headerName: 'Ativo?', sortable: false, renderCell: row => row.active ? 'Sim' : 'Não' },
]

export default function ContactPreferencesPage() {
  const navigate = useNavigate()
  const [preferencias, setPreferencias] = useState<Record<string, unknown>[]>([])
  const [loading, setLoading] = useState(false)
  const [pagination, setPagination] = useState<PaginationState>({ page: 1, rowsPerPage: 10, rowsNumber: 0 })

  useEffect(() => {
    const fetch = async () => {
      setLoading(true)
      try {
        const resp = await apiClientes.get(
          `/clientes-api/v1/customers-management/contact-preferences/search?page=${pagination.page}&size=${pagination.rowsPerPage}`
        )
        setPreferencias(resp.data.content ?? [])
        setPagination(p => ({ ...p, rowsNumber: resp.data.totalElements ?? 0 }))
      } catch (error: unknown) {
        if ((error as { response?: { status: number } }).response?.status === 403) navigate('/admin')
      } finally {
        setLoading(false)
      }
    }
    fetch()
  }, [pagination.page, pagination.rowsPerPage])

  return (
    <Box>
      <Typography variant="h4" sx={{ mb: 0.5 }}>Preferências de Contato</Typography>
      <Typography variant="caption" color="text.secondary" sx={{ mb: 2, display: 'block' }}>
        Importante para processo de Esqueci Minha Senha
      </Typography>
      <Button variant="contained" startIcon={<FilterListIcon />} sx={{ mb: 2 }}>Filtros</Button>
      <ServerTable
        rows={preferencias}
        columns={columns}
        loading={loading}
        pagination={pagination}
        onPaginationChange={setPagination}
        noDataLabel="Nenhuma preferência de contato encontrada."
      />
    </Box>
  )
}
